---
sidebar: sidebar
permalink: 1_overview_how_rest_apis_work.html
keywords: script, scripts, scripting, api request, api response, json schema, authentication, api, restful, restful API, rest API, rest, error codes, api parameters, netapp, cloud, ontap, Cloud Volumes ONTAP, manager, management, oncommand, storage
summary: OnCommand Cloud Manager includes REST APIs that enable software developers to automate the management of Cloud Volumes ONTAP. You should understand how the APIs work before you get started.
---

= How the REST APIs work
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
OnCommand Cloud Manager includes REST APIs that enable software developers to automate the management of Cloud Volumes ONTAP. You should understand how the APIs work before you get started.

== API resources
The Cloud Manager APIs enable you to perform operations on different types of resources. The resources are broadly categorized as follows:

* *Administrative resources*  +
Used to set up and configure Cloud Manager
* *Auditing resources* +
Used to view details about Cloud Manager operations
* *Authentication resources* +
Used to authenticate with Cloud Manager so you can run API operations
* *Working environment resources* +
Used to deploy and manage working environments: single Cloud Volumes ONTAP systems, Cloud Volumes ONTAP HA configurations, and ONTAP clusters

== API endpoint
Cloud Manager API URLs are relative to _http://ip_address:port/occm/api_.

For example, the request URL to a launch Cloud Volumes ONTAP in AWS is _http://ip_address:port/occm/api/vsa/working-environments_.

== API request and response formats
The REST API issues calls through HTTP requests and responses. The HTTP message body carries data objects in readable strings, in the default JSON (JavaScript Object Notation) format.

Responses can be a JSON object, or an array of JSON objects.

The format of a JSON object is as follows:
----
{
    name: "string"
}
----

The format of an array of JSON objects is as follows:
----
[
    {name: "string"}, {name: "string"}
]
----

== Header fields
You must specify the Content-Type field in the header for each API call. The Accept field is optional. Both fields must be set to *application/json* for most API calls:
----
Accept: application/json
Content-Type: application/json
----

NOTE: The server automatically returns content in JSON format if Accept is not specified.

The API reference identifies when Content-Type and Accept must be set to different values. For example, for backup API calls, Content-Type must be set to *multiport/form-data* and for restore API calls, Accept must be set to *application/octet-stream*.

Each API returns a custom HTTP header field named OnCloud-Request-Id. You can use the value of this field to track the progress of requests using the audit API calls.

== Public IDs
All Cloud Manager resources (for example, users, tenants, and working environments) are assigned a public ID. Whenever a resource is created or returned, the public ID is displayed in the response. You must specify a resource's public ID when performing operations on the resource. For example, you must specify the public ID for a working environment when you create a volume.

== HTTP status codes

[cols="1,4"]
|===
|HTTP code |Description

|200
|The operation was completed successfully and the API sent a response.

|202
|The operation was accepted and is currently in process. Cloud Manager returns this code when the API operation returns before the actual operation finishes. For example, the _/vsa/working-environments_ operation returns with code 202, but the Cloud Volumes ONTAP instance successfully launches up to 25 minutes later.

|204
|The operation was completed successfully and the API did not send a response.

|400
|There was an error with the client’s request. An error response explains the reason.

|401
|The user has not authenticated.

|403
|The user has authenticated but does not have permissions to perform the operation on the resource.

|409
|The operation failed because another operation is already in progress.

|420
|Cloud Manager has not been set up. You must set up Cloud Manager using the API call _/occm/setup/init_

|5xx
|An error occurred with the Cloud Manager server.
|===

== URI scheme
*Host*: localhost

*BasePath*: /occm/api

*Schemes*: HTTP

== Authentication with NetApp Cloud Central
Most API operations require an authentication header that specifies a token. The token identifies the client/caller.

Before you can get the token, you need to obtain the domain and client IDs from Cloud Manager. You can obtain the IDs by calling the support-services API.

After you obtain the IDs, you can then invoke Cloud Manager's authentication API to get the token.

The following example first obtains the domain and client IDs and then invokes the authentication API:

----
curl -X GET http://localhost/occm/api/occm/system/support-services |jq -r .portalService.auth0Information > info.txt

clientId=`cat info.txt|jq -r .clientId`
domain=`cat info.txt|jq -r .domain`
audience=`cat info.txt|jq -r .audience`
curl  https://$domain/oauth/token -X POST --header "Content-Type:application/json" --data "{\"grant_type\": \"password\",\"username\": \"$email\",\"password\": \"$password\",\"audience\": \"$audience\",\"scope\": \"profile\",\"client_id\": \"$clientId\"}" | jq -r .access_token > token.txt

token+=`cat token.txt`
----

NOTE: This new authentication method was introduced in Cloud Manager 3.5. Previous versions of Cloud Manager used a cookie for authentication. That login method is still supported, but we recommend using this new authentication method.
