---
sidebar: sidebar
permalink: concept_backup_to_cloud.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, back up volumes, Backup to Cloud, restore volumes, billing, cost
summary: Backup to Cloud is an add-on service for Cloud Volumes ONTAP that delivers backup and restore capabilities for protection, and long-term archive of your cloud data. Backups are stored in an object store in your account, independent of volume Snapshot copies used for near-term recovery or cloning.
---

= Learn about Backup to Cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Backup to Cloud is an add-on service for Cloud Volumes ONTAP that delivers backup and restore capabilities for protection, and long-term archive of your cloud data. Backups are stored in an object store in your cloud account, independent of volume Snapshot copies used for near-term recovery or cloning.

Backup to Cloud is powered by the https://cloud.netapp.com/cloud-backup-service[Cloud Backup Service^].

NOTE: You must use Cloud Manager for all backup and restore operations. Any actions taken directly from ONTAP or from your cloud provider results in an unsupported configuration.

== Features

* Back up independent copies of your data volumes to low-cost object storage in the cloud.
+
Backup data is secured with AES-256 bit encryption at-rest and TLS 1.2 HTTPS connections in-flight.
* Restore data from a specific point in time.
* Restore the data to the source Cloud Volumes ONTAP system or to a different system.

== Supported object storage providers

Backup to Cloud is supported with the following types of working environments:

* Cloud Volumes ONTAP in AWS
* Cloud Volumes ONTAP in Azure

== Cost

Backup to Cloud is available in two pricing options: Bring Your Own License (BYOL) and Pay As You Go (PAYGO).

For BYOL you'll pay NetApp to use the service for a period of time, say 6 months, and for a maximum amount backup capacity, say 10 GB (before storage efficiencies). You'll receive a serial number that you enter in the Cloud Manager Licensing page to enable the service. When either limit is reached you'll need to renew the license. See link:task_managing_backups.html#adding_and_updating_your_backup_byol_license[Adding and updating your Backup BYOL license]. The Backup BYOL license applies to all Cloud Volumes ONTAP systems associated with your link:concept_cloud_central_accounts.html[Cloud Central account].

For PAYGO you'll need to pay your cloud provider for object storage costs and NetApp for backup licensing costs. The licensing costs are based on used capacity (before storage efficiencies):

* AWS: A 30-day free trial is available. https://aws.amazon.com/marketplace/pp/B07QX2QLXX[Go to the Cloud Manager Marketplace offering for pricing details^].

* Azure: A 30-day free trial is available. https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-manager?tab=Overview[Go to the Cloud Manager Marketplace offering for pricing details^].

== How Backup to Cloud works

When you enable Backup to Cloud on a Cloud Volumes ONTAP system, the service performs a full backup of your data. After the initial backup, all additional backups are incremental, which means that only changed blocks and new blocks are backed up.

=== Where backups reside

Backup copies are stored in an S3 bucket or Azure Blob container that Cloud Manager creates in your cloud account. The object store is created in the same region where the Cloud Volumes ONTAP system is located. There's one object store per Cloud Volumes ONTAP system.

Cloud Manager names the object store as follows: netapp-backup-_clusteruuid_

Be sure not to delete this object store.

Notes:

* In AWS, Cloud Manager enables the https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-block-public-access.html[Amazon S3 Block Public Access feature^] on the S3 bucket.

* In Azure, Cloud Manager creates a new resource group with a storage account for the Blob container.

=== Supported S3 storage classes

In Amazon S3, backups start in the _Standard_ storage class and transition to the _Standard-Infrequent Access_ storage class after 30 days.

=== Supported Azure Blob access tiers

In Azure, each backup is associated with the _cold_ access tier.

=== Backup settings are system wide

When you enable Backup to Cloud, _all_ supported volumes on the system are backed up to the cloud.

The schedule and number of backups to retain are defined at the system level. The backup settings affect all volumes on the system.

=== The schedule is daily, _or_ weekly, _or_ monthly

You can choose daily, or weekly, or monthly backups of all volumes. You can also select one of the system-defined policies that provide scheduled backups for 3 months, 1 year, and 7 years.

Note that the retention period for backups of data protection volumes is the same as defined in the source SnapMirror relationship. You can change this if you want by using the API.

=== Backups are taken at midnight

* Daily backups start just after midnight each day.

* Weekly backups start just after midnight on Sunday mornings.

* Monthly backups start just after midnight on the first of each month.

At this time, you can’t schedule backup operations at a user specified time.

=== Backup copies are associated with your Cloud Central account

Backup copies are associated with the link:concept_cloud_central_accounts.html[Cloud Central account] in which Cloud Manager resides.

If you have multiple Cloud Manager systems in the same Cloud Central account, each Cloud Manager system will display the same list of backups. That includes the backups associated with Cloud Volumes ONTAP instances from other Cloud Manager systems.

=== BYOL license considerations

When using a Backup to Cloud BYOL license, Cloud Manager notifies you when backups are nearing the capacity limit or nearing the license expiration date. You receive these notifications:

* when backups have reached 80% of licensed capacity, and again when you have reached the limit
* 30 days before a license is due to expire, and again when the license expires

Use the chat icon in the lower right of the Cloud Manager interface to renew your license when you receive these notifications.

Two things can happen when your license expires:

* If the account you are using for your Cloud Volumes ONTAP systems has a marketplace account, the backup service continues to run, but you are shifted over to a PAYGO licensing model. You are charged by your cloud provider for object storage costs, and by NetApp for backup licensing costs, for the capacity that your backups are using.
* If the account you are using for your Cloud Volumes ONTAP systems does not have a marketplace account, the backup service continues to run, but you will continue to receive the expiration message.

Once you renew your BYOL subscription, Cloud Manager automatically obtains the new license from NetApp and installs it. If Cloud Manager can't access the license file over the secure internet connection, you can obtain the file yourself and manually upload the file to Cloud Manager. For instructions, see link:task_managing_backups.html#adding_and_updating_your_backup_byol_license[Adding and updating your Backup BYOL license].

Systems that were shifted over to a PAYGO license are returned to the BYOL license automatically. And systems that were running without a license will stop receiving the warning message and will be charged for backups that occurred while the license was expired.

=== Supported volumes

Backup to Cloud supports read-write volumes only.

FlexGroup volumes aren't currently supported.

== Limitations

* Volumes that you create outside of Cloud Manager aren't automatically backed up.
+
For example, if you create a volume from the ONTAP CLI, ONTAP API, or System Manager, then the volume won't be automatically backed up.
+
If you want to back up these volumes, you would need to disable Backup to Cloud and then enable it again.

* Backup to Cloud can maintain up to 1,019 total backups of a volume.

* In Azure, if you enable Backup to Cloud when Cloud Volumes ONTAP is deployed, Cloud Manager creates the resource group for you and you cannot change it. If you want to pick your own resource group when enabling Backup to Cloud, *disable* Backup to Cloud when deploying Cloud Volumes ONTAP and then enable Backup to Cloud and choose the resource group from the Backup to Cloud Settings page.

* WORM storage is not supported on a Cloud Volumes ONTAP system when Backup to Cloud is enabled.
