---
sidebar: sidebar
permalink: concept_overview.html
keywords: overview, concepts, features, use case
summary: Cloud Manager enables you to deploy Cloud Volumes ONTAP, which provides enterprise-class features for your cloud storage, and to easily replicate data across hybrid clouds built on NetApp.
---

= Learn about Cloud Manager
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

Cloud Manager enables IT experts and cloud architects to centrally manage their hybrid multi-cloud infrastructure using NetApp's cloud solutions.

== Features

Cloud Manager is an enterprise-class, SaaS-based management platform that keeps you in control of your data no matter where it is.

* Set up and use Cloud Volumes ONTAP for efficient, multi-protocol data management across clouds.
* Set up and use file-storage services: Azure NetApp Files and Cloud Volumes Service for AWS.
* Discover and manage your on-prem ONTAP clusters by creating volumes, replicating data across your hybrid cloud, and tiering cold data to the cloud.
* Enable integrated cloud services and software like Cloud Compliance, Cloud Insights, Cloud Backup Service, Trident, and more.

https://www.netapp.com/us/products/data-infrastructure-management/cloud-manager.aspx[Learn more about Cloud Manager^]

== Supported object storage providers

Cloud Manager enables you to manage cloud storage and use cloud services in Amazon Web Services, Microsoft Azure, and Google Cloud.

== Cost

Cloud Manager software is free of charge from NetApp.

For most tasks, Cloud Manager prompts you to deploy a Connector in your cloud network, which results in charges from your cloud provider for the compute instance and associated storage. You do have the option to run the Connector software on your premises.

== How Cloud Manager works

Cloud Manager includes a SaaS-based interface that is integrated with NetApp Cloud Central, and Connectors that manage Cloud Volumes ONTAP and other cloud services.

<image coming soon>

=== Software-as-a-service

Cloud Manager is accessible through a https://cloudmanager.netapp.com[SaaS-based user interface] and APIs. This SaaS experience enables you to automatically access the latest features as they're released and to easily switch between your Cloud Central accounts and Connectors.

=== NetApp Cloud Central

https://cloud.netapp.com[NetApp Cloud Central^] provides a centralized location to access and manage https://www.netapp.com/us/products/cloud-services/use-cases-for-netapp-cloud-services.aspx[NetApp cloud services^]. With centralized user authentication, you can use the same set of credentials to access Cloud Manager and other cloud services like Cloud Insights.

When you log in to Cloud Manager for the first time, you're prompted to create a )_Cloud Central account_. This account provides multi-tenancy and enables you to organize users and resources in isolated _workspaces_.

<image coming soon>

=== Connectors

In most cases, you will need to deploy a _Connector_ in your cloud or on-premises network. The Connector enables Cloud Manager to manage resources and processes within your public cloud environment.

A Connector should remain running at all times. It's important for the continued health and operation of the services that you enable.

For example, each Connector is a key component in the health and operation of Cloud Volumes ONTAP. If a Connector is powered down, Cloud Volumes ONTAP systems will shut down after losing communication with a Connector for longer than 14 days.

link:concept_connectors.html[Learn more about when Connectors are required and how they work].
