---
sidebar: sidebar
permalink: concept_evaluating.html
keywords: free trial, evaluation, license, evaluate
summary: You can evaluate Cloud Volumes ONTAP before you pay for the software. If you intend to pay hourly, then you should use a free trial. If you intend to purchase a license, then you should start with an evaluation license.
---

= Free trials and evaluation licenses
:toc: macro
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can evaluate Cloud Volumes ONTAP before you pay for the software. If you intend to pay hourly, then you should use a free trial. If you intend to purchase a license, then you should start with an evaluation license.

toc::[]

== Free trials

A free trial is a good choice if you plan to pay for Cloud Volumes ONTAP as you go. You can start a 30-day free trial of a single-node Cloud Volumes ONTAP system from https://cloud.netapp.com[NetApp Cloud Central].

There are no hourly software charges for that instance, but AWS infrastructure charges still apply. A free trial automatically converts to a paid hourly subscription when it expires.

== Evaluation licenses

An evaluation license is available for customers who expect to pay for Cloud Volumes ONTAP with a license. You can obtain an evaluation license from your account team or from a Sales Engineer.

If you do not provide Cloud Manager with a regular license before the evaluation license expires, the Cloud Volumes ONTAP system shuts itself down until you enter a valid license. Data is not deleted from the system.

link:concept_licensing.html[Learn more about licensing]
