---
sidebar: sidebar
permalink: reference_new_otc.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements
---

= What's new in ONTAP Cloud
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

New releases of ONTAP Cloud introduce new features, enhancements, and bug fixes.

You can find information about known issues and limitations in the https://library.netapp.com/ecm/ecm_get_file/ECMLP2839309[ONTAP Cloud 9.3 for AWS Release Notes^] and https://library.netapp.com/ecm/ecm_get_file/ECMLP2839308[ONTAP Cloud 9.3 for Azure Release Notes^].

// toc::[]

== ONTAP Cloud 9.3

ONTAP Cloud 9.3 includes several new features and enhancements.

=== ONTAP Cloud HA enhancements in AWS

The 9.3 release addresses the resiliency of ONTAP Cloud HA pairs to tolerate network glitches or transient higher latencies within the AWS ecosystem, and to ensure the availability of customer data during such events.

=== Support for the EU (Paris) region in AWS

ONTAP Cloud is now supported in the EU (Paris) region in AWS. Based on the supported instance types in this region, the following ONTAP Cloud configurations are available in the EU (Paris) region:

* ONTAP Cloud Standard (r4.xlarge)
* ONTAP Cloud Premium (r4.2xlarge)
* ONTAP Cloud BYOL (r4.xlarge and r4.2xlarge)

=== Enhanced write performance with Azure Premium disks

Write performance for ONTAP Cloud has been improved in Azure when using Premium Storage disks. The enhancement is supported with ONTAP Cloud Standard, Premium, and BYOL.

NOTE: Write performance enhancements are not supported when using the DS3_v2 virtual machine type.

=== Increased capacity limit for ONTAP Cloud Premium and BYOL in Azure

The capacity limit for ONTAP Cloud Premium and ONTAP Cloud BYOL has doubled to 252 TB when using the DS5_v2 or DS14_v2 virtual machine types.

NOTE: This change is possible due to an increase in the number of disks available per Azure virtual machine. It does not change the maximum capacity per aggregate.

=== Support for Azure US Gov regions

You can now deploy Cloud Manager and ONTAP Cloud BYOL in the following Azure regions:

* US Gov Arizona
* US Gov Texas
* US Gov Virginia

To deploy Cloud Manager in these regions, you must create a CentOS 7.3 virtual machine from the Azure Marketplace, download the Cloud Manager installer from the NetApp Support Site, and then install the software. After Cloud Manager is running, you can deploy ONTAP Cloud BYOL systems in the these regions just like any other region.

=== Support for SVM disaster recovery

ONTAP Cloud supports one data-serving Storage Virtual Machine (SVM) and one or more SVMs used for disaster recovery.

SVM disaster recovery is the asynchronous mirroring of SVM data and configuration from a source SVM to a destination SVM. You can quickly activate a destination SVM for data access if the source SVM is no longer available.

NOTE: Cloud Manager does not provide any setup or orchestration support for SVM disaster recovery.

https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856[ONTAP Cloud 9.3 SVM Disaster Recovery Preparation Express Guide^]

https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857[ONTAP Cloud 9.3 SVM Disaster Recovery Express Guide^]

=== Upgrade notes

* You can upgrade to ONTAP Cloud 9.3 from ONTAP Cloud 9.1 or ONTAP Cloud 9.2. You can perform the upgrade directly from Cloud Manager.

* When you use Cloud Manager to upgrade a single ONTAP Cloud system, the upgrade process takes the ONTAP Cloud system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrades of ONTAP Cloud HA pairs in AWS are nondisruptive. A nondisruptive upgrade upgrades both nodes in an HA pair concurrently while maintaining service to clients.
