---
sidebar: sidebar
permalink: reference_before.html
keywords: prerequisites, requirements, before
summary: Before you use Cloud Manager to create and manage Cloud Volumes ONTAP systems, your Cloud Manager administrator should have prepared networking and installed and set up Cloud Manager.
---

= Before you create Cloud Volumes ONTAP systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Before you use Cloud Manager to create and manage Cloud Volumes ONTAP systems, your Cloud Manager administrator should have prepared networking and installed and set up Cloud Manager.

The following conditions should exist before you start deploying Cloud Volumes ONTAP:

* Networking requirements were met for Cloud Manager and Cloud Volumes ONTAP.
* Cloud Manager has permissions to perform operations in your chosen cloud provider.
* Cloud Manager was installed.
+
TIP: link:concept_keep_up.html[Cloud Manager should remain running at all times].

.Related links

* link:task_getting_started_aws.html[Getting started in AWS]
* link:task_getting_started_azure.html[Getting started in Azure]
* link:task_getting_started_gcp.html[Getting started in GCP]
* link:task_setting_up_cloud_manager.html[Setting up Cloud Manager]
