---
sidebar: sidebar
permalink: reference_networking_gcp.html
keywords: networking, network, requirements, connection, connections, subnet, vpn, internet, proxy, HTTP, private, proxy server, routing, firewall, autosupport, connection, jump host, outbound, ports, tiering, data tiering, bucket, private google access, set up data tiering, data tiering requirement, gcp networking, google networking, shared vpc, host project, service project
summary: Set up your Google Cloud Platform networking so Cloud Volumes ONTAP systems can operate properly.
---

= Networking requirements for Cloud Volumes ONTAP in GCP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Set up your Google Cloud Platform networking so Cloud Volumes ONTAP systems can operate properly.

== Networking requirements

The following requirements must be met in GCP.

Shared VPC::
Cloud Manager and Cloud Volumes ONTAP are supported in a Google Cloud Platform shared VPC.
+
A shared VPC enables you to configure and centrally manage virtual networks across multiple projects. You can set up shared VPC networks in the _host project_ and deploy the Cloud Manager and Cloud Volumes ONTAP virtual machine instances in a _service project_. https://cloud.google.com/vpc/docs/shared-vpc[Google Cloud documentation: Shared VPC overview^].
+
The only requirement is to provide the https://cloud.google.com/compute/docs/access/iam#compute.networkUser[Compute Network User role^] to the Cloud Manager service account.
+
Cloud Manager needs these permissions to query the firewalls, VPC, and subnets in the host project.

Outbound internet access for Cloud Volumes ONTAP::
Cloud Volumes ONTAP requires outbound internet access to send messages to NetApp AutoSupport, which proactively monitors the health of your storage.
+
Routing and firewall policies must allow HTTP/HTTPS traffic to the following endpoints so Cloud Volumes ONTAP can send AutoSupport messages:
+
* \https://support.netapp.com/aods/asupmessage
* \https://support.netapp.com/asupprod/post/1.0/postAsup
+
link:task_setting_up_ontap_cloud.html[Learn how to configure AutoSupport].

Number of IP addresses::
Cloud Manager allocates 5 IP addresses to Cloud Volumes ONTAP in GCP.
+
Note that Cloud Manager doesn't create an SVM management LIF for Cloud Volumes ONTAP in GCP.
+
TIP: A LIF is an IP address associated with a physical port. An SVM management LIF is required for management tools like SnapCenter.

Firewall rules::
You don't need to create firewall rules because Cloud Manager does that for you. If you need to use your own, refer to link:reference_firewall_rules_gcp.html[GCP firewall rules].

Connection from Cloud Volumes ONTAP to Google Cloud Storage for data tiering::
If you want to tier cold data to a Google Cloud Storage bucket, the subnet in which Cloud Volumes ONTAP resides must be configured for Private Google Access. For instructions, refer to https://cloud.google.com/vpc/docs/configure-private-google-access[Google Cloud documentation: Configuring Private Google Access^].
+
For additional steps required to set up data tiering in Cloud Manager, see link:task_tiering.html[Tiering cold data to low-cost object storage].

Connections to ONTAP systems in other networks::
To replicate data between a Cloud Volumes ONTAP system in GCP and ONTAP systems in other networks, you must have a VPN connection between the VPC and the other network—for example, your corporate network.
+
For instructions, refer to https://cloud.google.com/vpn/docs/concepts/overview[Google Cloud documentation: Cloud VPN overview^].

== Firewall rules for Cloud Volumes ONTAP

Cloud Manager creates GCP firewall rules that include the inbound and outbound rules that Cloud Manager and Cloud Volumes ONTAP need to operate successfully. You might want to refer to the ports for testing purposes or if you prefer your to use own security groups.

The firewall rules for Cloud Volumes ONTAP requires both inbound and outbound rules.

=== Inbound rules for Cloud Volumes ONTAP

The source for inbound rules in the predefined security group is 0.0.0.0/0.

[cols="10,10,80",width=100%,options="header"]
|===

| Protocol
| Port
| Purpose

| All ICMP | All | Pinging the instance
| HTTP | 80 |	HTTP access to the System Manager web console using the IP address of the cluster management LIF
| HTTPS |	443 |	HTTPS access to the System Manager web console using the IP address of the cluster management LIF
| SSH |	22 | SSH access to the IP address of the cluster management LIF or a node management LIF
| TCP |	111 |	Remote procedure call for NFS
| TCP |	139 | NetBIOS service session for CIFS
| TCP |	161-162 |	Simple network management protocol
| TCP |	445 |	Microsoft SMB/CIFS over TCP with NetBIOS framing
| TCP |	635 |	NFS mount
| TCP |	749 |	Kerberos
| TCP |	2049 |	NFS server daemon
| TCP |	3260 |	iSCSI access through the iSCSI data LIF
| TCP |	4045 |	NFS lock daemon
| TCP | 4046 | Network status monitor for NFS
| TCP |	10000 |	Backup using NDMP
| TCP |	11104 |	Management of intercluster communication sessions for SnapMirror
| TCP | 11105 | SnapMirror data transfer using intercluster LIFs
| UDP |	111 | Remote procedure call for NFS
| UDP |	161-162 |	Simple network management protocol
| UDP |	635 |	NFS mount
| UDP |	2049 | NFS server daemon
| UDP |	4045 | NFS lock daemon
| UDP | 4046 | Network status monitor for NFS
| UDP | 4049 | NFS rquotad protocol

|===

=== Outbound rules for Cloud Volumes ONTAP

The predefined security group for Cloud Volumes ONTAP opens all outbound traffic. If that is acceptable, follow the basic outbound rules. If you need more rigid rules, use the advanced outbound rules.

==== Basic outbound rules

The predefined security group for Cloud Volumes ONTAP includes the following outbound rules.

[cols=3*,options="header",width=70%,cols="20,20,60"]
|===

| Protocol
| Port
| Purpose

| All ICMP |	All |	All outbound traffic
| All TCP |	All |	All outbound traffic
| All UDP |	All |	All outbound traffic

|===

==== Advanced outbound rules

If you need rigid rules for outbound traffic, you can use the following information to open only those ports that are required for outbound communication by Cloud Volumes ONTAP.

NOTE: The source is the interface (IP address) on the Cloud Volumes ONTAP system.

[cols="10,10,6,20,20,34",width=100%,options="header"]
|===

| Service
| Protocol
| Port
| Source
| Destination
| Purpose

.18+| Active Directory | TCP | 88 | Node management LIF | Active Directory forest | Kerberos V authentication
| UDP | 137 | Node management LIF | Active Directory forest | NetBIOS name service
| UDP | 138 | Node management LIF | Active Directory forest | NetBIOS datagram service
| TCP | 139 | Node management LIF | Active Directory forest | NetBIOS service session
| TCP & UDP | 389 | Node management LIF | Active Directory forest | LDAP
| TCP | 445 | Node management LIF | Active Directory forest | Microsoft SMB/CIFS over TCP with NetBIOS framing
| TCP | 464 | Node management LIF | Active Directory forest | Kerberos V change & set password (SET_CHANGE)
| UDP | 464 | Node management LIF | Active Directory forest | Kerberos key administration
| TCP | 749 | Node management LIF | Active Directory forest | Kerberos V change & set Password (RPCSEC_GSS)
| TCP | 88 | Data LIF (NFS, CIFS, iSCSI) | Active Directory forest | Kerberos V authentication
| UDP | 137 | Data LIF (NFS, CIFS) | Active Directory forest | NetBIOS name service
| UDP | 138 | Data LIF (NFS, CIFS) | Active Directory forest | NetBIOS datagram service
| TCP | 139 | Data LIF (NFS, CIFS) | Active Directory forest | NetBIOS service session
| TCP & UDP | 389 | Data LIF (NFS, CIFS) | Active Directory forest | LDAP
| TCP | 445 | Data LIF (NFS, CIFS) | Active Directory forest | Microsoft SMB/CIFS over TCP with NetBIOS framing
| TCP | 464 | Data LIF (NFS, CIFS) | Active Directory forest | Kerberos V change & set password (SET_CHANGE)
| UDP | 464 | Data LIF (NFS, CIFS) | Active Directory forest | Kerberos key administration
| TCP | 749 | Data LIF (NFS, CIFS) | Active Directory forest | Kerberos V change & set password (RPCSEC_GSS)
.3+| Cluster | All traffic | All traffic | All LIFs on one node | All LIFs on the other node | Intercluster communications (Cloud Volumes ONTAP HA only)
| TCP | 3000 | Node management LIF | HA mediator | ZAPI calls (Cloud Volumes ONTAP HA only)
| ICMP | 1 | Node management LIF | HA mediator | Keep alive (Cloud Volumes ONTAP HA only)
| DHCP | UDP | 68 | Node management LIF | DHCP | DHCP client for first-time setup
| DHCPS | UDP | 67 | Node management LIF | DHCP | DHCP server
| DNS | UDP | 53 | Node management LIF and data LIF (NFS, CIFS) | DNS | DNS
| NDMP | TCP | 18600–18699 | Node management LIF | Destination servers | NDMP copy
| SMTP | TCP | 25 | Node management LIF | Mail server | SMTP alerts, can be used for AutoSupport
.4+| SNMP | TCP | 161 | Node management LIF | Monitor server | Monitoring by SNMP traps
| UDP | 161 | Node management LIF | Monitor server | Monitoring by SNMP traps
| TCP | 162 | Node management LIF | Monitor server | Monitoring by SNMP traps
| UDP | 162 | Node management LIF | Monitor server | Monitoring by SNMP traps
.2+| SnapMirror | TCP | 11104 | Intercluster LIF | ONTAP intercluster LIFs | Management of intercluster communication sessions for SnapMirror
| TCP | 11105 | Intercluster LIF | ONTAP intercluster LIFs | SnapMirror data transfer
| Syslog | UDP | 514 | Node management LIF | Syslog server | Syslog forward messages

|===
