---
sidebar: sidebar
permalink: reference_new_occm.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements
summary: OnCommand Cloud Manager typically introduces a new release every month to bring you new features, enhancements, and bug fixes.
---

= What's new in Cloud Manager 3.6
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
OnCommand Cloud Manager typically introduces a new release every month to bring you new features, enhancements, and bug fixes.

//toc::[]

TIP: Looking for a previous release?
link:https://docs.netapp.com/us-en/occm35/reference_new_occm.html[What's new in 3.5^]
link:https://docs.netapp.com/us-en/occm34/reference_new_occm.html[What's new in 3.4^]

== Cloud Manager 3.6 (4 Nov 2018)

Cloud Manager 3.6 includes a new feature.

=== Using Cloud Volumes ONTAP as persistent storage for a Kubernetes cluster

Cloud Manager can now automate the deployment of https://netapp-trident.readthedocs.io/en/stable-v18.10/introduction.html[NetApp Trident^] on a single Kubernetes cluster so you can use Cloud Volumes ONTAP as persistent storage for containers. Users can then request and manage Persistent Volumes using native Kubernetes interfaces and constructs, while taking advantage of ONTAP's advanced data management features without having to know anything about it.

link:task_persistent_volumes.html[Learn how to connect Cloud Volumes ONTAP systems to a Kubernetes cluster]
