---
sidebar: sidebar
permalink: reference_before.html
keywords: prerequisites, requirements, before
summary: Before you use Cloud Manager to create and manage ONTAP Cloud systems, your Cloud Manager administrator should have prepared networking and installed and set up Cloud Manager.
---

= Before you create ONTAP Cloud systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

Before you use Cloud Manager to create and manage ONTAP Cloud systems, your Cloud Manager administrator should have prepared networking and installed and set up Cloud Manager.

The following conditions should exist before you get started:

* AWS and Azure networking requirements were met for Cloud Manager and ONTAP Cloud.

* Cloud Manager has permissions to perform operations in AWS and Azure on your behalf.

* Each ONTAP Cloud product that users will deploy was subscribed to from the AWS Marketplace.

* Cloud Manager was installed.

* (Optional) Additional tenants were defined.

* (Optional) Additional user accounts were created, which can include Tenant Admins and Working Environment Admins.

* (Optional) If users want to enable ONTAP Cloud encryption in AWS, a key management infrastructure was set up and Cloud Manager encryption settings were defined.
