---
sidebar: sidebar
permalink: reference_additional_info.html
keywords: community, forums, help, support, videos, policies, json, api, ontap, release notes, bugs, limitations, known issues, permissions, apis
summary: You can get help and find more information about Cloud Manager and ONTAP Cloud through various resources, including videos, forums, and support.
---

= Where to get help and find more information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can get help and find more information about Cloud Manager and ONTAP Cloud through various resources, including videos, forums, and support.

* https://www.youtube.com/playlist?list=PLdXI3bZJEw7lnoRo8FBKsX1zHbK8AQOoT[Videos for Cloud Manager and ONTAP Cloud^]
+
Watch videos that show you how to deploy and manage ONTAP Cloud in AWS and Azure and how to replicate data across your hybrid cloud.

* http://mysupport.netapp.com/cloudontap/support/iampolicies[Policies for Cloud Manager^]
+
Download JSON files that include the permissions that Cloud Manager needs to perform actions in AWS and Azure.

* https://library.netapp.com/ecmdocs/ECMLP2839258/html/index.html[Cloud Manager API Developer Guide^]
+
Read an overview of the APIs, examples of how to use them, and an API reference.

* Release Notes
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839255[Cloud Manager 3.4 Release Notes^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839309[ONTAP Cloud 9.3 for AWS Release Notes^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839308[ONTAP Cloud 9.3 for Azure Release Notes^]
+
Read about known issues and limitations that affect Cloud Manager and ONTAP Cloud.

* http://docs.netapp.com/ontap-9/index.jsp[ONTAP 9 Documentation Center^]
+
Access product documentation for ONTAP, which can help you as you use ONTAP Cloud.

* https://mysupport.netapp.com/cloudontap[NetApp ONTAP Cloud Support^]
+
Access support resources to get help and troubleshoot issues with ONTAP Cloud.

* http://community.netapp.com/hybrid-cloud[NetApp Community: Hybrid Cloud^]
+
Connect with peers, ask questions, exchange ideas, find resources, and share best practices.
