---
sidebar: sidebar
permalink: reference_new_occm.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes
summary: Cloud Manager typically introduces a new release every month to bring you new features, enhancements, and bug fixes.
---

= What's new in Cloud Manager 3.7
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Manager typically introduces a new release every month to bring you new features, enhancements, and bug fixes.

TIP: Looking for a previous release?
link:https://docs.netapp.com/us-en/occm36/reference_new_occm.html[What's new in 3.6^]
link:https://docs.netapp.com/us-en/occm35/reference_new_occm.html[What's new in 3.5^]
link:https://docs.netapp.com/us-en/occm34/reference_new_occm.html[What's new in 3.4^]

== Cloud Manager 3.7.3 update (15 Sept 2019)

Cloud Manager now enables you to back up data from Cloud Volumes ONTAP to Amazon S3.

Backup to S3 is an add-on feature for Cloud Volumes ONTAP that delivers fully-managed backup and restore capabilities for protection, and long-term archive of your cloud data. Backups are stored in S3 object storage, independent of volume Snapshot copies used for near-term recovery or cloning. The feature is powered by NetApp's Cloud Backup Service.

link:task_backup_to_s3.html[Learn how to get started].

This feature requires an update to the https://mysupport.netapp.com/cloudontap/iampolicies[Cloud Manager policy^]. The following VPC endpoint permissions are now required:

[source,json]
"ec2:DescribeVpcEndpoints",
"ec2:CreateVpcEndpoint",
"ec2:ModifyVpcEndpoint",
"ec2:DeleteVpcEndpoints"

== Cloud Manager 3.7.3 (11 Sept 2019)

Cloud Manager 3.7.3 includes the following enhancements.

* <<Discovery and management of Cloud Volumes Service for AWS>>
* <<New subscription required in the AWS Marketplace>>
* <<Support for AWS GovCloud (US-East)>>

=== Discovery and management of Cloud Volumes Service for AWS

Cloud Manager now enables you to discover the cloud volumes in your https://cloud.netapp.com/cloud-volumes-service-for-aws[Cloud Volumes Service for AWS^] subscription. After discovery, you can add additional cloud volumes directly from Cloud Manager. This enhancement provides a single pane of glass from which you can manage your NetApp cloud storage.

link:task_manage_cvs_aws.html[Learn how to get started].

=== New subscription required in the AWS Marketplace

https://aws.amazon.com/marketplace/pp/B07QX2QLXX[A new subscription is available in the AWS Marketplace^]. This one-time subscription is required to deploy Cloud Volumes ONTAP 9.6 PAYGO (except for your 30-day free trial system). The subscription also enables us to offer add-on features for Cloud Volumes ONTAP PAYGO and BYOL. You'll be charged from this subscription for every Cloud Volumes ONTAP PAYGO system that you create and each add-on feature that you enable.

Starting with version 9.6, this new subscription method replaces the two existing AWS Marketplace subscriptions for Cloud Volumes ONTAP PAYGO to which you previously subscribed. You still need subscriptions through the https://aws.amazon.com/marketplace/search/results?x=0&y=0&searchTerms=cloud+volumes+ontap+byol[existing AWS Marketplace pages when deploying Cloud Volumes ONTAP BYOL^].

link:reference_aws_marketplace.html[Learn more about each AWS Marketplace page].

=== Support for AWS GovCloud (US-East)

Cloud Manager and Cloud Volumes ONTAP are now supported in the AWS GovCloud (US-East) region.

== General Availability of Cloud Volumes ONTAP in GCP (3 Sept 2019)

Cloud Volumes ONTAP is now generally available in Google Cloud Platform (GCP) when you bring your own license (BYOL). A pay-as-you-go promotion is also available. The promotion offers free licenses for an unlimited number of systems and will expire at the end of September 2019.

* link:task_getting_started_gcp.html[Learn how to get started in GCP]
* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_gcp_96.html[View supported configurations^]

== Cloud Manager 3.7.2 (5 Aug 2019)

* <<FlexCache licenses>>
* <<Kubernetes storage classes for iSCSI>>
* <<Management of inodes>>
* <<Support for the Hong Kong region in AWS>>
* <<Support for the Australia Central regions in Azure>>

=== FlexCache licenses

Cloud Manager now generates a FlexCache license for all new Cloud Volumes ONTAP systems. The license includes a 500 GB usage limit.

To generate the license, Cloud Manager needs to access \https://ipa-signer.cloudmanager.netapp.com. Make sure that this URL is accessible from your firewall.

=== Kubernetes storage classes for iSCSI

When you connect Cloud Volumes ONTAP to a Kubernetes cluster, Cloud Manager now creates two additional Kubernetes storage classes that you can use with iSCSI Persistent Volumes:

* *netapp-file-san*: For binding iSCSI Persistent Volumes to single-node Cloud Volumes ONTAP systems
* *netapp-file-redundant-san*: For binding iSCSI Persistent Volumes to Cloud Volumes ONTAP HA pairs

=== Management of inodes

Cloud Manager now monitors the number of inodes on a volume and increases the maximum number when needed.  The number of files a volume can contain is determined by how many inodes it has.

=== Support for the Hong Kong region in AWS

Cloud Manager and Cloud Volumes ONTAP are now supported in the Asia Pacific (Hong Kong) region in AWS.

=== Support for the Australia Central regions in Azure

Cloud Manager and Cloud Volumes ONTAP are now supported in the following Azure regions:

* Australia Central
* Australia Central 2

https://cloud.netapp.com/cloud-volumes-global-regions[See the full list of supported regions^].

== Update on backing up and restoring (15 July 2019)

Starting with the 3.7.1 release, Cloud Manager no longer supports downloading a backup and using it to restore your Cloud Manager configuration. link:task_restoring.html[You need to follow these steps to restore Cloud Manager].

== Cloud Manager 3.7.1 (1 July 2019)

* This release primarily includes bug fixes.

* It does include one enhancement: Cloud Manager now installs a NetApp Volume Encryption (NVE) license on each Cloud Volumes ONTAP system that is registered with NetApp Support (both new and existing systems).
+
** link:task_adding_nss_accounts.html[Adding NetApp Support Site accounts to Cloud Manager]
** link:task_registering.html[Registering pay-as-you-go systems]
** link:task_encrypting_volumes.html[Setting up NetApp Volume Encryption]
+
NOTE: Cloud Manager does not install the NVE license on systems that reside in the China region.

== Cloud Manager 3.7 update (16 June 2019)

Cloud Volumes ONTAP 9.6 is now available in AWS, Azure, and in Google Cloud Platform as a private preview. To join the private preview, send a request to ng-Cloud-Volume-ONTAP-preview@netapp.com.

https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_new_96.html[See what's new in Cloud Volumes ONTAP 9.6^]

== Cloud Manager 3.7 (5 June 2019)

* <<Support for upcoming Cloud Volumes ONTAP 9.6 release>>
* <<NetApp Cloud Central accounts>>
* <<Backup and restore with the Cloud Backup Service>>

=== Support for upcoming Cloud Volumes ONTAP 9.6 release

Cloud Manager 3.7 includes support for the upcoming Cloud Volumes ONTAP 9.6 release. The 9.6 release includes a private preview of Cloud Volumes ONTAP in Google Cloud Platform. We'll update the release notes when 9.6 is available.

=== NetApp Cloud Central accounts

We've enhanced how you manage your cloud resources. Each Cloud Manager system will be associated with a _NetApp Cloud Central account_. The account enables multi-tenancy and is planned for other NetApp cloud data services in the future.

In Cloud Manager, a Cloud Central account is a container for your Cloud Manager systems and the _workspaces_ in which users deploy Cloud Volumes ONTAP.

link:concept_cloud_central_accounts.html[Learn how Cloud Central accounts enable multi-tenancy].

NOTE: Cloud Manager needs access to _\https://cloudmanager.cloud.netapp.com_ in order to connect to the Cloud Central account service. Open this URL on your ﬁrewall to ensure that Cloud Manager can contact the service.

==== Integrating your system with Cloud Central accounts

Some time after you upgrade to Cloud Manager 3.7, NetApp will choose specific Cloud Manager systems to integrate with Cloud Central accounts. During this process, NetApp creates an account, assigns new roles to each user, creates workspaces, and places existing working environments in those workspaces. There's no disruption to your Cloud Volumes ONTAP systems.

link:concept_cloud_central_accounts.html#faq[If you have questions, refer to this FAQ].

=== Backup and restore with the Cloud Backup Service

The NetApp Cloud Backup Service for Cloud Volumes ONTAP delivers fully-managed backup and restore capabilities for protection and long-term archive of your cloud data. You can integrate the Cloud Backup Service with Cloud Volumes ONTAP for AWS. Backups created by the service are stored in AWS S3 object storage.

https://cloud.netapp.com/cloud-backup-service[Learn more about the Cloud Backup Service^].

To get started, install and configure the backup agent and then start backup and restore operations. If you need help, we encourage you to contact us by using the chat icon in Cloud Manager.

NOTE: This manual process is no longer supported. The Backup to S3 feature was integrated into Cloud Manager in the 3.7.3 release.
