---
sidebar: sidebar
permalink: reference_new_occm.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes
summary: Cloud Manager typically introduces a new release every month to bring you new features, enhancements, and bug fixes.
---

= What's new in Cloud Manager 3.7
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Manager typically introduces a new release every month to bring you new features, enhancements, and bug fixes.

TIP: Looking for a previous release?
link:https://docs.netapp.com/us-en/occm36/reference_new_occm.html[What's new in 3.6^]
link:https://docs.netapp.com/us-en/occm35/reference_new_occm.html[What's new in 3.5^]
link:https://docs.netapp.com/us-en/occm34/reference_new_occm.html[What's new in 3.4^]

== Update on backing up and restoring (15 July 2019)

Starting with the 3.7.1 release, Cloud Manager no longer supports downloading a backup and using it to restore your Cloud Manager configuration. link:task_restoring.html[You need to follow these steps to restore Cloud Manager].

== Cloud Manager 3.7.1 (1 July 2019)

* This release primarily includes bug fixes.

* It does include one enhancement: Cloud Manager now installs a NetApp Volume Encryption (NVE) license on each Cloud Volumes ONTAP system that is registered with NetApp Support (both new and existing systems).
+
** link:task_adding_nss_accounts.html[Adding NetApp Support Site accounts to Cloud Manager]
** link:task_registering.html[Registering pay-as-you-go systems]
** link:task_encrypting_volumes.html[Setting up NetApp Volume Encryption]
+
NOTE: Cloud Manager does not install the NVE license on systems that reside in the China region.

== Cloud Manager 3.7 update (16 June 2019)

Cloud Volumes ONTAP 9.6 is now available in AWS, Azure, and in Google Cloud Platform as a private preview. To join the private preview, send a request to ng-Cloud-Volume-ONTAP-preview@netapp.com.

https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_new_96.html[See what's new in Cloud Volumes ONTAP 9.6^]

== Cloud Manager 3.7 (5 June 2019)

* <<Support for upcoming Cloud Volumes ONTAP 9.6 release>>
* <<NetApp Cloud Central accounts>>
* <<Backup and restore with the Cloud Backup Service>>

=== Support for upcoming Cloud Volumes ONTAP 9.6 release

Cloud Manager 3.7 includes support for the upcoming Cloud Volumes ONTAP 9.6 release. The 9.6 release includes a private preview of Cloud Volumes ONTAP in Google Cloud Platform. We'll update the release notes when 9.6 is available.

=== NetApp Cloud Central accounts

We've enhanced how you manage your cloud resources. Each Cloud Manager system will be associated with a _NetApp Cloud Central account_. The account enables multi-tenancy and is planned for other NetApp cloud data services in the future.

In Cloud Manager, a Cloud Central account is a container for your Cloud Manager systems and the _workspaces_ in which users deploy Cloud Volumes ONTAP.

link:concept_cloud_central_accounts.html[Learn how Cloud Central accounts enable multi-tenancy].

NOTE: Cloud Manager needs access to _\https://cloudmanager.cloud.netapp.com_ in order to connect to the Cloud Central account service. Open this URL on your ﬁrewall to ensure that Cloud Manager can contact the service.

==== Integrating your system with Cloud Central accounts

Some time after you upgrade to Cloud Manager 3.7, NetApp will choose specific Cloud Manager systems to integrate with Cloud Central accounts. During this process, NetApp creates an account, assigns new roles to each user, creates workspaces, and places existing working environments in those workspaces. There's no disruption to your Cloud Volumes ONTAP systems.

link:concept_cloud_central_accounts.html#faq[If you have questions, refer to this FAQ].

=== Backup and restore with the Cloud Backup Service

The NetApp Cloud Backup Service for Cloud Volumes ONTAP delivers fully-managed backup and restore capabilities for protection and long-term archive of your cloud data. You can integrate the Cloud Backup Service with Cloud Volumes ONTAP for AWS. Backups created by the service are stored in AWS S3 object storage.

https://cloud.netapp.com/cloud-backup-service[Learn more about the Cloud Backup Service^].

To get started, link:task_setting_up_cbs.html[install and configure the backup agent and then start backup and restore operations]. If you need help, we encourage you to contact us by using the chat icon in Cloud Manager.
