---
sidebar: sidebar
permalink: reference_security_groups_azure.html
keywords: security group, security groups, rules, ports, azure, inbound, outbound, rules
summary: Cloud Manager creates Azure security groups that include the inbound and outbound rules that Cloud Manager and Cloud Volumes ONTAP need to operate successfully. You might want to refer to the ports for testing purposes or if you need to use your own.
translate: false
---

= Security group rules for Azure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Manager creates Azure security groups that include the inbound and outbound rules that Cloud Manager and Cloud Volumes ONTAP need to operate successfully. You might want to refer to the ports for testing purposes or if you prefer your to use own security groups.

== Rules for Cloud Manager

The security group for Cloud Manager requires both inbound and outbound rules.

=== Inbound rules for Cloud Manager

The source for inbound rules in the predefined security group is 0.0.0.0/0.

[cols=3*,options="header,autowidth"]
|===

| Port
| Protocol
| Purpose

| 22 | SSH | Provides SSH access to the Cloud Manager host
| 80 | HTTP |	Provides HTTP access from client web browsers to the Cloud Manager web console
| 443 |	HTTPS | Provides HTTPS access from client web browsers to the Cloud Manager web console

|===

=== Outbound rules for Cloud Manager

The predefined security group for Cloud Manager opens all outbound traffic. If that is acceptable, follow the basic outbound rules. If you need more rigid rules, use the advanced outbound rules.

==== Basic outbound rules

The predefined security group for Cloud Manager includes the following outbound rules.

[cols=3*,options="header,autowidth"]
|===

| Port
| Protocol
| Purpose

| All | All TCP | All outbound traffic
| All |	All UDP | All outbound traffic

|===

==== Advanced outbound rules

If you need rigid rules for outbound traffic, you can use the following information to open only those ports that are required for outbound communication by Cloud Manager.

NOTE: The source IP address is the Cloud Manager host.

[cols=5*,options="header,autowidth"]
|===

| Service
| Port
| Protocol
| Destination
| Purpose

.9+| Active Directory | 88 | TCP | Active Directory forest | Kerberos V authentication
| 139 | TCP | Active Directory forest | NetBIOS service session
| 389 | TCP	| Active Directory forest | LDAP
| 445 | TCP	| Active Directory forest | Microsoft SMB/CIFS over TCP with NetBIOS framing
| 464 | TCP	| Active Directory forest | Kerberos V change & set password (SET_CHANGE)
| 749 | TCP	| Active Directory forest | Active Directory Kerberos V change & set password (RPCSEC_GSS)
| 137 | UDP	| Active Directory forest | NetBIOS name service
| 138 | UDP	| Active Directory forest | NetBIOS datagram service
| 464 | UDP	| Active Directory forest | Kerberos key administration
| API calls and AutoSupport | 443 | HTTPS | Outbound internet and ONTAP cluster management LIF | API calls to AWS and ONTAP, and sending AutoSupport messages to NetApp
| API calls | 3000 | TCP	| ONTAP cluster management LIF | API calls to ONTAP
| DNS | 53 | UDP	| DNS | Used for DNS resolve by Cloud Manager

|===

== Rules for Cloud Volumes ONTAP

The security group for Cloud Volumes ONTAP requires both inbound and outbound rules.

=== Inbound rules for single node systems

The rules listed below allow traffic, unless the description notes that it blocks specific inbound traffic.

[cols=4*,options="header,autowidth"]

|===
| Priority and name
| Port and protocol
| Source and destination
| Description

| 1000
inbound_ssh | 22
TCP | Any to Any | SSH access to the IP address of the cluster management LIF or a node management LIF
| 1001
inbound_http | 80
TCP | Any to Any | HTTP access to the System Manager web console using the IP address of the cluster management LIF
| 1002
inbound_111_tcp | 111
TCP | Any to Any | Remote procedure call for NFS
| 1003
inbound_111_udp | 111
UDP | Any to Any | Remote procedure call for NFS
| 1004
inbound_139 | 139
TCP | Any to Any | NetBIOS service session for CIFS
| 1005
inbound_161-162 _tcp | 161-162
TCP | Any to Any | Simple network management protocol
| 1006
inbound_161-162 _udp | 161-162
UDP | Any to Any | Simple network management protocol
| 1007
inbound_443 | 443
TCP | Any to Any | HTTPS access to the System Manager web console using the IP address of the cluster management LIF
| 1008
inbound_445 | 445
TCP | Any to Any | Microsoft SMB/CIFS over TCP with NetBIOS framing
| 1009
inbound_635_tcp | 635
TCP | Any to Any | NFS mount
| 1010
inbound_635_udp | 635
UDP | Any to Any | NFS mount
| 1011
inbound_749 | 749
TCP | Any to Any | Kerberos
| 1012
inbound_2049_tcp | 2049
TCP | Any to Any | NFS server daemon
| 1013
inbound_2049_udp | 2049
UDP | Any to Any | NFS server daemon
| 1014
inbound_3260 | 3260
TCP | Any to Any | iSCSI access through the iSCSI data LIF
| 1015
inbound_4045-4046_tcp | 4045-4046
TCP | Any to Any | NFS lock daemon and network status monitor
| 1016
inbound_4045-4046_udp | 4045-4046
UDP | Any to Any | NFS lock daemon and network status monitor
| 1017
inbound_10000 | 10000
TCP | Any to Any | Backup using NDMP
| 1018
inbound_11104-11105 | 11104-11105
TCP | Any to Any | SnapMirror data transfer
| 3000
inbound_deny _all_tcp | Any port
TCP | Any to Any | Block all other TCP inbound traffic
| 3001
inbound_deny _all_udp | Any port
UDP | Any to Any | Block all other UDP inbound traffic
| 65000
AllowVnetInBound | Any port
Any protocol | VirtualNetwork to VirtualNetwork | Inbound traffic from within the VNet
| 65001
AllowAzureLoad BalancerInBound  | Any port
Any protocol | AzureLoadBalancer to Any | Data traffic from the Azure Standard Load Balancer
| 65500
DenyAllInBound | Any port
Any protocol | Any to Any | Block all other inbound traffic

|===

=== Inbound rules for HA systems

The rules listed below allow traffic, unless the description notes that it blocks specific inbound traffic.

NOTE: HA systems have less inbound rules than single node systems because inbound data traffic goes through the Azure Standard Load Balancer. Because of this, traffic from the Load Balancer should be open, as shown in the "AllowAzureLoadBalancerInBound" rule.

[cols=4*,options="header,autowidth"]

|===
| Priority and name
| Port and protocol
| Source and destination
| Description

| 100
inbound_443 | 443
Any protocol | Any to Any | HTTPS access to the System Manager web console using the IP address of the cluster management LIF
| 101
inbound_111_tcp | 111
Any protocol | Any to Any | Remote procedure call for NFS
| 102
inbound_2049_tcp | 2049
Any protocol | Any to Any | NFS server daemon
| 111
inbound_ssh | 22
Any protocol | Any to Any | SSH access to the IP address of the cluster management LIF or a node management LIF
| 121
inbound_53 | 53
Any protocol | Any to Any | DNS and CIFS
| 65000
AllowVnetInBound | Any port
Any protocol | VirtualNetwork to VirtualNetwork | Inbound traffic from within the VNet
| 65001
AllowAzureLoad BalancerInBound | Any port
Any protocol | AzureLoadBalancer to Any | Data traffic from the Azure Standard Load Balancer
| 65500
DenyAllInBound | Any port
Any protocol | Any to Any | Block all other inbound traffic

|===

=== Outbound rules for Cloud Volumes ONTAP

The predefined security group for Cloud Volumes ONTAP opens all outbound traffic. If that is acceptable, follow the basic outbound rules. If you need more rigid rules, use the advanced outbound rules.

==== Basic outbound rules

The predefined security group for Cloud Volumes ONTAP includes the following outbound rules.

[cols=3*,options="header,autowidth"]
|===

| Port
| Protocol
| Purpose

|	All | All TCP |	All outbound traffic
|	All | All UDP |	All outbound traffic

|===

==== Advanced outbound rules

If you need rigid rules for outbound traffic, you can use the following information to open only those ports that are required for outbound communication by Cloud Volumes ONTAP.

NOTE: The source is the interface (IP address) on the Cloud Volumes ONTAP system.

[cols="10,10,10,20,20,40",width=100%,options="header"]
|===

| Service
| Port
| Protocol
| Source
| Destination
| Purpose

.18+| Active Directory | 88 | TCP | Node management LIF | Active Directory forest | Kerberos V authentication
| 137 | UDP | Node management LIF | Active Directory forest | NetBIOS name service
| 138 | UDP | Node management LIF | Active Directory forest | NetBIOS datagram service
| 139 | TCP | Node management LIF | Active Directory forest | NetBIOS service session
| 389 | TCP | Node management LIF | Active Directory forest | LDAP
| 445 | TCP | Node management LIF | Active Directory forest | Microsoft SMB/CIFS over TCP with NetBIOS framing
| 464 | TCP | Node management LIF | Active Directory forest | Kerberos V change & set password (SET_CHANGE)
| 464 | UDP | Node management LIF | Active Directory forest | Kerberos key administration
| 749 | TCP | Node management LIF | Active Directory forest | Kerberos V change & set Password (RPCSEC_GSS)
| 88 | TCP | Data LIF (NFS, CIFS) | Active Directory forest | Kerberos V authentication
| 137 | UDP | Data LIF (NFS, CIFS) | Active Directory forest | NetBIOS name service
| 138 | UDP | Data LIF (NFS, CIFS) | Active Directory forest | NetBIOS datagram service
| 139 | TCP | Data LIF (NFS, CIFS) | Active Directory forest | NetBIOS service session
| 389 | TCP | Data LIF (NFS, CIFS) | Active Directory forest | LDAP
| 445 | TCP | Data LIF (NFS, CIFS) | Active Directory forest | Microsoft SMB/CIFS over TCP with NetBIOS framing
| 464 | TCP | Data LIF (NFS, CIFS) | Active Directory forest | Kerberos V change & set password (SET_CHANGE)
| 464 | UDP | Data LIF (NFS, CIFS) | Active Directory forest | Kerberos key administration
| 749 | TCP | Data LIF (NFS, CIFS) | Active Directory forest | Kerberos V change & set password (RPCSEC_GSS)
| DHCP | 68 | UDP | Node management LIF | DHCP | DHCP client for first-time setup
| DHCPS | 67 | UDP | Node management LIF | DHCP | DHCP server
| DNS | 53 | UDP | Node management LIF and data LIF (NFS, CIFS) | DNS | DNS
| NDMP | 18600–18699 | TCP | Node management LIF | Destination servers | NDMP copy
| SMTP | 25 | TCP | Node management LIF | Mail server | SMTP alerts, can be used for AutoSupport
.4+| SNMP | 161 | TCP | Node management LIF | Monitor server | Monitoring by SNMP traps
| 161 | UDP | Node management LIF | Monitor server | Monitoring by SNMP traps
| 162 | TCP | Node management LIF | Monitor server | Monitoring by SNMP traps
| 162 | UDP | Node management LIF | Monitor server | Monitoring by SNMP traps
.2+| SnapMirror | 11104 | TCP | Intercluster LIF | ONTAP intercluster LIFs | Management of intercluster communication sessions for SnapMirror
| 11105 | TCP | Intercluster LIF | ONTAP intercluster LIFs | SnapMirror data transfer
| Syslog | 514 | UDP | Node management LIF | Syslog server | Syslog forward messages

|===
