---
sidebar: sidebar
permalink: reference_new_occm.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes
summary: Cloud Manager typically introduces a new release every month to bring you new features, enhancements, and bug fixes.
---

= What's new in Cloud Manager 3.7
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Manager typically introduces a new release every month to bring you new features, enhancements, and bug fixes.

TIP: Looking for a previous release?
link:https://docs.netapp.com/us-en/occm36/reference_new_occm.html[What's new in 3.6^]
link:https://docs.netapp.com/us-en/occm35/reference_new_occm.html[What's new in 3.5^]
link:https://docs.netapp.com/us-en/occm34/reference_new_occm.html[What's new in 3.4^]

== Cloud Manager 3.7 (4 June 2019)

* <<Support for upcoming Cloud Volumes ONTAP 9.6 release>>
* <<NetApp Cloud Central accounts>>
* <<Backup and restore with the Cloud Backup Service>>

=== Support for upcoming Cloud Volumes ONTAP 9.6 release

Cloud Manager 3.7 includes support for the upcoming Cloud Volumes ONTAP 9.6 release. This release includes a private preview of Cloud Volumes ONTAP in Google Cloud Platform. We'll update the release notes when 9.6 is available.

=== NetApp Cloud Central accounts

We've enhanced how you manage your cloud resources. Each Cloud Manager system is now associated with a _NetApp Cloud Central account_. A Cloud Central account provides the highest level of multi-tenancy for Cloud Manager and is planned for other NetApp cloud data services in the future.

In Cloud Manager, a Cloud Central account is a container for the _workspaces_ in which users deploy Cloud Volumes ONTAP systems. A workspace is similar to what was previously called a tenant.

You can create as many Cloud Central accounts as you need for your business. You might have one, or a few. For example, you might have two Cloud Manager systems, each deployed in separate Cloud Central accounts to serve different business needs.

link:concept_cloud_central_accounts.html[Learn more about NetApp Cloud Central accounts and workspaces].

==== Integrating your system with Cloud Central accounts

Some time after you upgrade to Cloud Manager 3.7, NetApp will choose specific Cloud Manager systems to integrate with Cloud Central accounts. During this process, NetApp creates an account, assigns new roles to each user, creates workspaces, and places existing working environments in those workspaces. There's no disruption to your Cloud Volumes ONTAP systems. If you have questions, refer to link:concept_cloud_accounts.html#faq-for-integrating-existing-systems-with-netapp-cloud-accounts[this FAQ].

=== Backup and restore with the Cloud Backup Service

The NetApp Cloud Backup Service for Cloud Volumes ONTAP delivers fully-managed backup and restore capabilities for protection and long-term archive of your cloud data. You can integrate the Cloud Backup Service with Cloud Volumes ONTAP for AWS. Backups created by the service are stored in AWS S3 object storage.

https://cloud.netapp.com/cloud-backup-service[Learn more about the Cloud Backup Service^].

To get started, link:task_setting_up_cbs.html[install and configure the backup agent and then start backup and restore operations]. If you need help, we encourage you to contact us by using the chat icon in Cloud Manager.
