---
sidebar: sidebar
permalink: reference_new_occm.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements
summary: OnCommand Cloud Manager typically introduces a new release every month to bring you new features, enhancements, and bug fixes.
---

= What's new in Cloud Manager
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
OnCommand Cloud Manager typically introduces a new release every month to bring you new features, enhancements, and bug fixes.

== Cloud Manager 3.5

Cloud Manager 3.5 includes new features and enhancements.

* <<Support for ONTAP Cloud 9.4>>
* <<New permissions required for ONTAP Cloud 9.4>>
* <<Cloud Manager integration with NetApp Cloud Central>>
* <<Support for the m4.large instance type>>
* <<Marketplace image now based on RHEL 7.4>>

=== Support for ONTAP Cloud 9.4

You can now deploy new ONTAP Cloud 9.4 systems from Cloud Manager and upgrade your existing systems to the 9.4 release. Cloud Manager also provides support for https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_new_94.html[the new features introduced in ONTAP Cloud 9.4^].

=== New permissions required for ONTAP Cloud 9.4

Cloud Manager requires new permissions for key features in the ONTAP Cloud 9.4 release. To ensure that your Cloud Manager systems can deploy and manage ONTAP Cloud 9.4 systems, you must update your Cloud Manager policy by adding the following permissions:

* For AWS: "ec2:DescribeInstanceAttribute",
+
Cloud Manager uses this permission to verify that enhanced networking is enabled for supported instance types.

* For Azure: "Microsoft.Network/virtualNetworks/subnets/write",
+
Cloud Manager uses this permission to enable VNet service endpoints for data tiering.

You can find the entire list of required permissions in https://mysupport.netapp.com/info/web/ECMP11022837.html[the latest policies provided by NetApp^].

=== Cloud Manager integration with NetApp Cloud Central

When upgrading to Cloud Manager 3.5, NetApp will choose specific Cloud Manager systems to integrate with NetApp Cloud Central, if they are not already integrated. During this process, NetApp migrates all local user accounts in your Cloud Manager system to the centralized user authentication available in Cloud Central. After the upgrade is complete, you simply need to log in.

If you have questions, refer to link:reference_integration_faq.html[this FAQ].

=== Support for the m4.large instance type

Cloud Manager is now supported with the m4.large EC2 instance type. m3.large is no longer supported.

For a list of supported Cloud Manager configurations, see link:reference_cloud_mgr_reqs.html[Cloud Manager host requirements].

=== Marketplace image now based on RHEL 7.4

The operating system for the Cloud Manager marketplace image in AWS and Azure is now Red Hat Enterprise Linux 7.4.
