---
sidebar: sidebar
permalink: reference_cloud_mgr_reqs.html
keywords: configurations, ec2, vm, ports, ram, operating system, os, host, requirement, requirements, hypervisor, disk, space, mysql, centos, rhel, red hat, cpu, disk space, 3306
summary: The Connector software must run on a host that meets specific operating system requirements, RAM requirements, port requirements, and so on.
---

= Connector host requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Connector software must run on a host that meets specific operating system requirements, RAM requirements, port requirements, and so on.

NOTE: You can install a Connector on your own host in GCP, but not in your on-premises network. The Connector must be installed in GCP in order to deploy Cloud Volumes ONTAP in GCP.

A dedicated host is required::
The Connector is not supported on a host that is shared with other applications. The host must be a dedicated host.

CPU:: 4 cores or 4 vCPUs

RAM:: 14 GB

AWS EC2 instance type::
An instance type that meets the CPU and RAM requirements above. We recommend t3.xlarge and use that instance type when you deploy the Connector directly from Cloud Manager.

Azure VM size::
An instance type that meets the CPU and RAM requirements above. We recommend DS3 v2 and use that VM size when you deploy the Connector directly from Cloud Manager.

GCP machine type::
An instance type that meets the CPU and RAM requirements above. We recommend n1-standard-4  and use that machine type when you deploy the Connector directly from Cloud Manager.

Supported operating systems::
* CentOS 7.2
* CentOS 7.3
* CentOS 7.4
* CentOS 7.5
* CentOS 7.6
* CentOS 7.7
* Red Hat Enterprise Linux 7.2
* Red Hat Enterprise Linux 7.3
* Red Hat Enterprise Linux 7.4
* Red Hat Enterprise Linux 7.5
* Red Hat Enterprise Linux 7.6
* Red Hat Enterprise Linux 7.7
+
The Red Hat Enterprise Linux system must be registered with Red Hat Subscription Management. If it is not registered, the system cannot access repositories to update required 3rd party software during Connector installation.
+
The Connector is supported on English-language versions of these operating systems.

Hypervisor::  A bare metal or hosted hypervisor that is certified to run CentOS or Red Hat Enterprise Linux
https://access.redhat.com/certified-hypervisors[Red Hat Solution: Which hypervisors are certified to run Red Hat Enterprise Linux?^]

Free disk space in /opt:: 100 GB

Outbound internet access::
Outbound internet access is required to install the Connector and for the Connector to manage resources and processes within your public cloud environment. For a list of endpoints, see link:reference_networking_cloud_manager.html[Networking requirements for the Connector].

Ports::
The following ports must be available:
* 80 for HTTP access
* 443 for HTTPS access
* 3306 for the Cloud Manager database
* 8080 for the Cloud Manager API proxy
* 8666 for the Service Manager API
* 8777 for the Health-Checker Container Service API
+
If other services are using these ports, installation of the Connector fails.
+
NOTE: There is a potential conflict with port 3306. If another instance of MySQL is running on the host, it uses port 3306 by default. You must change the port that the existing MySQL instance uses.
+
You can change the default HTTP and HTTPS ports when you install a Connector. You can't change the default port for the MySQL database.
