---
sidebar: sidebar
permalink: reference_networking_azure.html
keywords: networking, network, requirements, connection, connections, vnet, security group, security groups, subnet, vpn, internet, proxy, HTTP, private, proxy server, routing, firewall, autosupport, connection, jump host, URL, URLs, endpoints, endpoint
summary: You must set up your Azure networking so that Cloud Manager can deploy ONTAP Cloud systems and so those systems can operate properly.
---

= Azure networking requirements
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You must set up your Azure networking so that Cloud Manager can deploy ONTAP Cloud systems and so those systems can operate properly.

Outbound internet access for Cloud Manager::
Cloud Manager requires outbound internet access to contact the following endpoints when deploying and managing ONTAP Cloud in Microsoft Azure:
+
[cols=2*,options="header",cols="50,50"]
|===
| Endpoint
| Purpose
|

\https://management.azure.com
\https://login.microsoftonline.com

| Enables Cloud Manager to deploy and manage ONTAP Cloud systems in most Azure regions.

|
\https://management.microsoftazure.de
\https://login.microsoftonline.de
| Enables Cloud Manager to deploy and manage ONTAP Cloud systems in the Azure Germany regions.

|
\https://management.usgovcloudapi.net
\https://login.microsoftonline.com
| Enables Cloud Manager to deploy and manage ONTAP Cloud systems in the Azure US Gov regions.

| s3.us-east-1.amazonaws.com	| Provides access to software images in Amazon S3 for upgrades.

|
cognito-idp.us-east-1.amazonaws.com
cognito-identity.us-east-1.amazonaws.com
| Enables Cloud Manager to access and download manifests, templates, and ONTAP Cloud upgrade images.

| kinesis.us-east-1.amazonaws.com	| Enables NetApp to stream data from audit records.

| \https://netapp-cloud-account.auth0.com | Communication with NetApp Cloud Central for centralized user authentication.

| \https://mysupport.netapp.com | Communication with NetApp AutoSupport.
|
\https://support.netapp.com/svcgw
\https://support.netapp.com/ServiceGW/entitlement
| Communication with NetApp for licensing and support registration.
|===
+
NOTE: If your network uses a proxy server for all communication to the internet, Cloud Manager prompts you to specify the proxy during setup. You can also specify the proxy server from the Settings page. Refer to link:task_configuring_proxy.html[Configuring Cloud Manager to use a proxy server].

Outbound internet access for ONTAP Cloud::
ONTAP Cloud requires outbound internet access to send messages to NetApp AutoSupport, which proactively monitors the health of your storage.
+
Routing and firewall policies must allow Azure HTTP/HTTPS traffic to mysupport.netapp.com so ONTAP Cloud can send AutoSupport messages.

Security groups::
You do not need to create security groups because Cloud Manager does that for you. If you need to use your own, refer to link:reference_security_groups_azure.html[Security group rules].

Connection between Cloud Manager and ONTAP Cloud subnets::
Cloud Manager requires a connection to the subnets in which you deploy ONTAP Cloud systems.
+
If Cloud Manager is not installed in the target VNet, it must have network connectivity to that VNet. For example, if you install Cloud Manager in AWS or in your corporate network, you must set up a VPN connection to the VNet in which you deploy ONTAP Cloud systems.

Connections to ONTAP systems in other networks::
To replicate data between an ONTAP Cloud system in Azure and ONTAP systems in other networks, you must have a VPN connection between the Azure VNet and the other network—for example, an AWS VPC or your corporate network.
+
https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-site-to-site-resource-manager-portal[Microsoft Azure Documentation: Create a Site-to-Site connection in the Azure portal^]

Connection to the Cloud Manager web console::
Users must access Cloud Manager from a web browser. If you deploy Cloud Manager in Azure, the easiest way to provide access is by allocating a public IP address. However, if you want to use a private IP address instead, users can access the console through either of the following:

* A jump host in the VNet that has a connection to Cloud Manager

* A host in your network that has a VPN connection to the private IP address
