---
sidebar: sidebar
permalink: task_migrating_to_portal.html
keywords: migrating, cloud central, portal, migrate, move, existing
summary: You can migrate to NetApp Cloud Central if you have an existing Cloud Manager system. You just need to deploy a new Cloud Manager system from Cloud Central and then discover existing ONTAP Cloud systems from the new Cloud Manager system.
---

= Migrating to NetApp Cloud Central
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can migrate to NetApp Cloud Central if you have an existing Cloud Manager system. You just need to deploy a new Cloud Manager system from Cloud Central and then discover existing ONTAP Cloud systems from the new Cloud Manager system.

.About this task

Cloud Manager's integration with NetApp Cloud Central provides several benefits, including a simplified deployment experience, a single location to view and manage multiple Cloud Manager systems, and centralized user authentication.

.Steps

. Deploy a new Cloud Manager system from the https://cloud.netapp.com[NetApp Cloud Central^].

. If needed, add user accounts to Cloud Manager.
+
link:task_setting_up_cloud_manager.html#adding-users-to-cloud-manager[Adding users to Cloud Manager]

. Discover existing ONTAP Cloud systems from the new Cloud Manager system.
+
link:task_adding_ontap_cloud.html[Adding existing ONTAP Cloud systems to Cloud Manager]

. Delete the old Cloud Manager system.
