---
sidebar: sidebar
permalink: task_launching_aws_mktp.html
keywords: install, installation, installing, marketplace, aws, launch, launching, ec2 console
summary: It is best to launch Cloud Manager in AWS using NetApp Cloud Central, but you can launch it from the AWS Marketplace, if needed.
---

= Launching Cloud Manager from the AWS Marketplace
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

It is best to launch Cloud Manager in AWS using https://cloud.netapp.com[NetApp Cloud Central^], but you can launch it from the AWS Marketplace, if needed.

TIP: If you launch Cloud Manager from the AWS Marketplace, Cloud Manager is still integrated with NetApp Cloud Central. link:concept_cloud_central.html[Learn more about the integration].

.Before you begin

If you want to assign a public IP address to the Cloud Manager instance and use the AWS 1-Click Launch option, the public subnet must be already enabled to automatically assign public IP addresses. Otherwise, you must use the Manual Launch option to assign a public IP address to the instance.

For details, refer to http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-ip-addressing.html[AWS Documentation: IP Addressing in Your VPC^].

.Steps

. Set up an IAM role that includes the required permissions.
+
link:task_granting_aws_permissions.html[Granting permissions when Cloud Manager is not launched from Cloud Central]

. Go to the https://aws.amazon.com/marketplace/pp/B018REK8QG[Cloud Manager page on the AWS Marketplace^].

. Click *Continue*.

. Launch the instance from the 1-Click Launch tab or the Custom Launch tab, depending on how you want to grant AWS permissions to Cloud Manager:
+
[cols=2*,options="header",cols="25,75"]
|===
| Choice
| Steps

| You want to associate the instance with an IAM role.
a|
.. On the Custom Launch tab, click *Launch with EC2 Console* for your region.

.. Choose the t2.medium or m4.large instance type.

.. Select a VPC, subnet, IAM role, and other configuration options that meet your requirements.

.. Keep the default storage options.

.. Enter tags for the instance, if desired.

.. Specify the required connection methods for the Cloud Manager instance: SSH, HTTP, and HTTPS.

.. Click *Launch*.

| You do not want to associate the instance with an IAM role. You want to specify AWS keys for each Cloud Manager user account.
a|
.. On the 1-Click Launch tab, specify settings for the instance. Note the following:

* The t2.medium and m4.large instance types are supported.

* Under security group, select *Create new based on seller settings* to create a pre-defined security group that includes the rules required by Cloud Manager.

.. Click *Accept Terms and Launch with 1-Click*.

|===

.Result

AWS launches the software with the specified settings. The Cloud Manager instance and software should be running in approximately five minutes.

.After you finish

Log in to Cloud Manager by entering the public IP address or private IP address in a web browser and then complete the Setup wizard.
