---
sidebar: sidebar
permalink: task_setting_up_cloud_manager.html
keywords:
summary: You can start creating Cloud Volumes ONTAP systems right after you deploy Cloud Manager. However, you might want to perform additional setup first by setting up your Cloud Central account, adding cloud provider accounts, installing an HTTPS certificate, and more.
---

= Setting up Cloud Manager
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can start creating Cloud Volumes ONTAP systems right after you deploy Cloud Manager. However, you might want to perform additional setup first by setting up your Cloud Central account, adding cloud provider accounts, installing an HTTPS certificate, and more.

* link:task_setting_up_cloud_central_accounts.html[Setting up your Cloud Central account]
* link:task_adding_aws_accounts.html[Adding AWS accounts to Cloud Manager]
* link:task_adding_azure_accounts.html[Adding Azure accounts to Cloud Manager]
* link:task_adding_gcp_accounts.html[Adding GCP accounts to Cloud Manager]
* link:task_adding_nss_accounts.html[Adding NetApp Support Site accounts to Cloud Manager]
* link:task_installing_https_cert.html[Installing an HTTPS certificate]
* link:task_setting_up_kms.html[Setting up the AWS KMS]
