---
sidebar: sidebar
permalink: task_adding_azure_subscriptions.html
keywords: microsoft, azure, permissions, subscriptions, managed service identity, iam, operator, role, virtual machine,
summary: Cloud Manager enables you to choose the Azure account and subscription in which you want to deploy Cloud Volumes ONTAP. You cannot select a different Azure subscription for a Managed Service Identity profile unless you associate the Managed Service Identity with those subscriptions.
---

= Associating additional Azure subscriptions with a Managed Service Identity
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Manager enables you to choose the Azure account and subscription in which you want to deploy Cloud Volumes ONTAP. You can't select a different Azure subscription for a Managed Service Identity profile unless you associate the Managed Service Identity with those subscriptions.

.About this task

A Managed Service Identity is the initial _Cloud Provider Account_ when you deploy Cloud Manager from NetApp Cloud Central. When you deployed Cloud Manager, Cloud Central created the OnCommand Cloud Manager Operator role and assigned it to the Cloud Manager virtual machine.

link:concept_accounts_and_permissions.html[Learn more about Cloud Provider Accounts and permissions].

.Steps

. Log in to the Azure portal.

. Open the *Subscriptions* service and then select the subscription in which you want to deploy Cloud Volumes ONTAP systems.

. Click *Access control (IAM)*.

. Click *Add* and then add the permissions:

* Select the *OnCommand Cloud Manager Operator* role.

* Assign access to a *Virtual Machine*.

* Select the subscription in which the Cloud Manager virtual machine was created.

* Select the Cloud Manager virtual machine.

* Click *Save*.

. Repeat these steps for additional subscriptions.

.Result

When you create a new working environment, you should now have the ability to select from multiple Azure subscriptions for the Managed Service Identity profile.

<screenshot>
