---
sidebar: sidebar
permalink: task_setting_up_permissions_aws.html
keywords: connector permissions, aws permissions, permissions for the connector
summary: A Connector enables Cloud Manager to manage resources and processes within your public cloud environment. Before you can deploy a Connector from Cloud Manager, you need to ensure that your AWS account has the correct permissions.
---

= Setting up AWS permissions to create a Connector
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
A Connector enables Cloud Manager to manage resources and processes within your public cloud environment. Before you can deploy a Connector from Cloud Manager, you need to ensure that your AWS account has the correct permissions.

.About this task

Follow these steps before you create a Connector directly from Cloud Manager. These steps don't apply if you're using one of the alternative ways to create a Connector.

If you're deploying the Connector from the AWS Marketplace, follow these steps instead.

If you're manually installing the Connector software on your own Linux host, follow these steps instead.

.Steps

. Download the Connector IAM policy from the following location:
+
https://mysupport.netapp.com/cloudontap/iampolicies[NetApp Cloud Manager: AWS, Azure, and GCP Policies^]

. From the AWS IAM console, create your own policy by copying and pasting the text from the Connector IAM policy.

. Attach the policy that you created in the previous step to the IAM user who will create the Connector from Cloud Manager.

.Result

The AWS user now has the permissions required to create the Connector from Cloud Manager. You'll need to specify AWS access keys for this user when you're prompted by Cloud Manager.
