---
sidebar: sidebar
permalink: task_scanning_onprem.html
keywords: cloud compliance, on-prem, scan on prem data, scan on-prem data
summary: You can scan your on-premises ONTAP data with Cloud Compliance by replicating the on-prem data to a Cloud Volumes ONTAP working environment and then enabling compliance. Scanning the data directly from an on-premises ONTAP working environment isn't supported.
---

= Scanning on-premises ONTAP data with Cloud Compliance by using SnapMirror
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can scan your on-premises ONTAP data with Cloud Compliance by replicating the on-prem NFS or CIFS data to a Cloud Volumes ONTAP working environment and then enabling compliance. Scanning the data directly from an on-premises ONTAP working environment isn't supported.

You must have link:task_deploy_cloud_compliance.html[deployed an instance of Cloud Compliance in Cloud Manager already^].

.Steps

. From Cloud Manager, create a SnapMirror relationship between the on-premises ONTAP cluster and Cloud Volumes ONTAP.

.. https://docs.netapp.com/us-en/occm/task_discovering_ontap.html[Discover the on-premises cluster in Cloud Manager^].

.. https://docs.netapp.com/us-en/occm/task_replicating_data.html[Create a SnapMirror replication between the on-premises ONTAP cluster and Cloud Volumes ONTAP from Cloud Manager^].

.	From Cloud Manager, activate Cloud Compliance on the Cloud Volumes ONTAP working environment that contains the SnapMirror data:
.. Click *Canvas*.
.. Select the working environment that contains the SnapMirror data and click *Enable Compliance*.
+
link:task_getting_started_compliance.html[Click here if you need help with enabling Cloud Compliance on a Cloud Volumes ONTAP system^].

. Click the *Enable Access to DP volumes* button at the top of the _Scan Configuration_ page so that Cloud Compliance can access the DP volumes.
+
NFS volumes are enabled, but CIFS volumes require that you enter Active Directory Admin credentials.

. Activate each DP volume that you want to scan, or use the *Activate Compliance for all Volumes* control to enable all volumes, including all DP volumes.

See link:task_getting_started_compliance.html#scanning-data-protection-volumes[Scanning data protection volumes^] for more information.
