---
sidebar: sidebar
permalink: task_setting_up_ontap_cloud.html
keywords: set up, setting up, ntp, time, synch, autosupport, asup, ems, lif, svm, backup, configuration files, config, snapcenter, snapdrive, ntp server, svm management lif, management lif
summary: After you deploy ONTAP Cloud, you can set it up by synchronizing the system time using NTP and by performing a few optional tasks from either System Manager or the CLI.
---

= Setting up ONTAP Cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

After you deploy ONTAP Cloud, you can set it up by synchronizing the system time using NTP and by performing a few optional tasks from either System Manager or the CLI.

[cols=2*,options="header",cols="30,70"]
|===
| Task

| Description

| Synchronize the system time using NTP |	ONTAP Cloud needs a Network Time Protocol (NTP) server to synchronize the time with clients and peered clusters. Problems can occur when the time is inaccurate.

You can configure the NTP server using System Manager or the CLI. For instructions, see the System Manager Help or the http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html[ONTAP 9 System Administration Reference^].

| Optional: Configure AutoSupport | AutoSupport proactively monitors the health of your system and automatically sends messages to NetApp technical support by default.

If the Cloud Manager Admin added a proxy server to Cloud Manager before you launched your instance, ONTAP Cloud is configured to use that proxy server for AutoSupport messages.

You should test AutoSupport to ensure that it can send messages. For instructions, see the System Manager Help or the http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html[ONTAP 9 System Administration Reference^].

| Optional: Configure EMS | The Event Management System (EMS) collects and displays information about events that occur on ONTAP Cloud systems. To receive event notifications, you can set event destinations (email addresses, SNMP trap hosts, or syslog servers) and event routes for a particular event severity.

You can configure EMS using the CLI. For instructions, see the http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-ems/home.html[ONTAP 9 EMS Configuration Express Guide^].

| Optional: Create an SVM management network interface (LIF)
a| If you want to use SnapDrive for Windows or SnapCenter with an ONTAP Cloud HA pair, you must create the storage virtual machine (SVM) management network interface (LIF) that SnapDrive and SnapCenter require. The SVM management LIF must use a floating IP address. You can create the LIF from System Manager or the CLI.

The following example shows how to create the LIF from the CLI:
....
network interface create -vserver svm_cloud -lif svm_mgmt -role data -data-protocol none -home-node cloud-01 -home-port e0a -address 10.0.2.126 -netmask 255.255.255.0 -status-admin up -firewall-policy mgmt
....

| Optional: Change the backup location of configuration files | ONTAP Cloud automatically creates configuration backup files that contain information about the configurable options that it needs to operate properly.

By default, ONTAP Cloud backs up the files to the Cloud Manager host every eight hours. If you want to send the backups to an alternate location, you can change the location to an FTP or HTTP server in your data center or in AWS. For example, you might already have a backup location for your FAS storage systems.

You can change the backup location using the CLI. See the http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html[ONTAP 9 System Administration Reference^].
|===
