---
sidebar: sidebar
permalink: task_installing_azure_gov.html
keywords: install, installation, installing, software, azure, us gov, gov
summary: To deploy Cloud Manager in an Azure US Gov region, you must download the Cloud Manager installer from the NetApp Support Site and install it on an existing CentOS 7.5 host.
---

= Installing Cloud Manager in an Azure US Gov region
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To deploy Cloud Manager in an Azure US Gov region, you must download the Cloud Manager installer from the NetApp Support Site and install it on an existing CentOS 7.5 host.

.About this task

For a list of supported Azure US Gov regions, see https://cloud.netapp.com/cloud-volumes-global-regions[Cloud Volumes Global Regions].

.Steps

. link:reference_networking_azure.html[Review networking requirements for Azure].

. Create a CentOS 7.5 virtual machine from the Azure Marketplace.
+
While Cloud Manager supports other operating systems, it currently supports CentOS 7.5 in the Azure US Gov regions.

. link:task_installing_linux.html[Download and install Cloud Manager].

. link:task_adding_cloud_accounts.html#setting-up-and-adding-azure-accounts-to-cloud-manager[Grant Azure permissions to Cloud Manager using a service principal].
+
NOTE: Managed Service Identities are currently in Preview in the US Gov regions.

.After you finish

Cloud Manager is now ready to deploy Cloud Volumes ONTAP in an Azure US Gov region, just like any other region. However, you might want to perform additional setup first.
