---
sidebar: sidebar
permalink: task_installing_azure_gov.html
keywords: install, installation, installing, software, azure, us gov, gov
summary: To deploy Cloud Manager in an Azure US Gov region, you must download the Cloud Manager installer from the NetApp Support Site and install it on an existing CentOS 7.3 host.
---

= Installing Cloud Manager in an Azure US Gov region
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To deploy Cloud Manager in an Azure US Gov region, you must download the Cloud Manager installer from the NetApp Support Site and install it on an existing CentOS 7.3 host.

.About this task

For a list of supported Azure US Gov regions, see link:reference_regions.html#supported-azure-regions[Supported Azure regions].

.Steps

. link:reference_networking_azure.html[Review networking requirements for Azure].

. Create a CentOS 7.3 virtual machine from the Azure Marketplace.
+
While Cloud Manager supports other operating systems, it only supports CentOS 7.3 in the Azure US Gov regions.

. link:task_installing_linux.html[Download and install Cloud Manager].

. link:task_creating_service_principal.html[Grant Azure permissions to Cloud Manager using a service principal and credentials].
+
NOTE: Managed Service Identities are not supported in the US Gov regions.

.After you finish

Cloud Manager is now ready to deploy Cloud Volumes ONTAP in an Azure US Gov region, just like any other region. However, you might want to perform additional setup first.
