---
sidebar: sidebar
permalink: task_installing_linux.html
keywords: install, installation, installing, linux, installer, software
---

= Installing Cloud Manager on an existing Linux host
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If you want to run the Cloud Manager software on an existing host, you can download and install the software on a Linux host in your network or in the cloud.

.About this task

* Root privileges are not required to install Cloud Manager.

* Cloud Manager installs the AWS command line tools (awscli) to enable recovery procedures from NetApp support.
+
If you receive a message that installing the awscli failed, you can safely ignore the message. Cloud Manager can operate successfully without the tools.

.Steps

. Review networking requirements for your cloud service provider:

* link:reference_networking_aws.html[AWS networking requirements]
* link:reference_networking_azure.html[Azure networking requirements]
* link:reference_networking_ibm.html[IBM Cloud networking requirements]

. Set up permissions for Cloud Manager:

.. If you want to deploy ONTAP Cloud systems in AWS, link:task_granting_aws_permissions.html[set up an IAM role that includes the required permissions].

.. If you want to deploy ONTAP Cloud systems in Azure, link:task_getting_started_azure.html#granting-azure-permissions-to-cloud-manager[create and set up a service principal in Azure Active Directory].

. Review link:reference_cloud_mgr_reqs.html[Cloud Manager host requirements].

. Download the software from the http://mysupport.netapp.com/NOW/cgi-bin/software[NetApp Support Site^], and then copy it to the Linux host.
+
For help with connecting and copying the file to an EC2 instance in AWS, see http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html[AWS Documentation: Connecting to Your Linux Instance Using SSH^].

. Assign permissions to execute the script.
+
*Example*
+
`chmod +x OnCommandCloudManager-V3.4.0.sh`

. Run the installation script:
+
``./OnCommandCloudManager-V3.4.0.sh [silent] [proxy=ipaddress] [proxyport=port] [proxyuser=user_name] [proxypwd=password]``
+
_silent_ runs the installation without prompting you for information.
+
_proxy_ is required if the Cloud Manager host is behind a proxy server.
+
_proxyport_ is the port for the proxy server.
+
_proxyuser_ is the user name for the proxy server, if basic authentication is required.
+
_proxypwd_ is the password for the user name that you specified.

. Unless you specified the silent parameter, type *Y* to continue the script, and then enter the HTTP and HTTPS ports when prompted.
+
If you change the HTTP and HTTPS ports, you must ensure that users can access the Cloud Manager web console from a remote host:

* Modify the security group to allow inbound connections through the ports.

* Specify the port when you enter the URL to the Cloud Manager web console.
+
Cloud Manager is now installed. At the end of the installation, the Cloud Manager service (occm) restarts twice if you specified a proxy server.

. Open a web browser and enter the following URL:
+
https://_ipaddress_:__port__
+
_ipaddress_ can be localhost, a private IP address, or a public IP address, depending on the configuration of the Cloud Manager host. For example, if Cloud Manager is in the public cloud without a public IP address, you must enter a private IP address from a host that has a connection to the Cloud Manager host.
+
_port_ is required if you changed the default HTTP (80) or HTTPS (443) ports. For example, if the HTTPS port was changed to 8443, you would enter https://_ipaddress_:8443

. Sign up for a NetApp Cloud Central account or log in if you already have one.

. When you sign up or log in, Cloud Manager automatically adds your user account as the administrator for this system.

. After you log in, enter a name for this Cloud Manager system.

.After you finish

You can start creating ONTAP Cloud systems but you might want to perform additional setup first.
