---
sidebar: sidebar
permalink: task_encrypting_volumes.html
keywords: encrypt, encryption, data, volumes, netapp volume encryption, volume encryption, nve, key managers, kmip, key management servers, license, ssl certificates, nae, netapp aggregate encryption
summary: Cloud Volumes ONTAP supports both NetApp Volume Encryption (NVE) and NetApp Aggregate Encryption (NAE) with an external key manager. NVE and NAE are enabled by default if you set up an external key manager.
---

= Encrypting volumes with NetApp encryption solutions
:toc: macro
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP supports both NetApp Volume Encryption (NVE) and NetApp Aggregate Encryption (NAE) with an external key manager. NVE and NAE are software-based solutions that enable (FIPS) 140-2–compliant data-at-rest encryption of volumes. link:concept_security.html[Learn more about these encryption solutions].

Starting with Cloud Volumes ONTAP 9.7, new aggregates will have NAE enabled by default after you set up an external key manager. New volumes that aren't part of an NAE aggregate will have NVE enabled by default (for example, if you have existing aggregates that were created before setting up an external key manager).

Cloud Volumes ONTAP doesn't support onboard key management.

.What you'll need

Your Cloud Volumes ONTAP system should be registered with NetApp support. Starting with Cloud Manager 3.7.1, a NetApp Volume Encryption license is automatically installed on each Cloud Volumes ONTAP system that is registered with NetApp Support.

* link:task_adding_nss_accounts.html[Adding NetApp Support Site accounts to Cloud Manager]
* link:task_registering.html[Registering pay-as-you-go systems]

NOTE: Cloud Manager doesn't install the NVE license on systems that reside in the China region.

.Steps

. Review the list of supported key managers in the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].
+
TIP: Search for the *Key Managers* solution.

. link:task_connecting_to_otc.html[Connect to the Cloud Volumes ONTAP CLI^].

. Install SSL certificates and connect to the external key management servers.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-DD718B42-038D-4009-84FF-20BBD6530BC2.html[ONTAP 9 NetApp Encryption Power Guide: Configuring external key management^]
