---
sidebar: sidebar
permalink: task_restoring.html
keywords: cloud manager, restore, restoring, restore cloud manager, back up, backup, backups, back up cloud manager
summary: NetApp Cloud Central accounts make it easy for you to restore a Cloud Manager configuration. The account is a service running in Cloud Central so the users, workspaces, and service connectors that you associated with the account are always accessible. Even if your Cloud Manager system was accidentally deleted.
---

= Restoring Cloud Manager
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Your link:concept_cloud_central_accounts.html[NetApp Cloud Central account] makes it easy for you to restore a Cloud Manager configuration. The account is a service running in Cloud Central so the users, workspaces, and service connectors that you associated with the account are always accessible. Even if your Cloud Manager system was accidentally deleted.

NOTE: Starting with the 3.7.1 release, Cloud Manager no longer supports downloading a backup and using it to restore your configuration. You need to follow these steps to restore Cloud Manager.

.Steps

. Deploy a new Cloud Manager system in your existing Cloud Central account.
+
link:reference_deployment_overview.html[Deployment options]

. Add your cloud provider accounts and NetApp Support Site accounts to Cloud Manager.
+
This step gets Cloud Manager ready so you can create additional Cloud Volumes ONTAP systems in your cloud provider.
+
It's important to complete this step if you used AWS keys to deploy an existing Cloud Volumes ONTAP system that you want to discover on this new Cloud Manager system. Cloud Manager needs the AWS keys to properly discover and manage Cloud Volumes ONTAP.
+
* link:task_adding_aws_accounts.html[Adding AWS accounts to Cloud Manager]
* link:task_adding_azure_accounts.html[Adding Azure accounts to Cloud Manager]
* link:task_adding_nss_accounts.html[Adding NetApp Support Site accounts to Cloud Manager]

. Rediscover your working environments: Cloud Volumes ONTAP systems, on-premises clusters, and NetApp Private Storage for Cloud configurations.
+
* link:task_adding_ontap_cloud.html[Adding existing Cloud Volumes ONTAP systems to Cloud Manager]
* link:task_discovering_ontap.html#discovering-ontap-clusters[Discovering ONTAP clusters]

.Result

Your Cloud Manager configuration is now restored with your accounts, settings, and working environments.
