---
sidebar: sidebar
permalink: task_provisioning_ontap.html
keywords: ontap, cluster, manage, provision, provisioning, volumes, discovering, fas, aff, creating volumes, adding volumes
summary: After you discover your on-prem ONTAP cluster from Cloud Manager, you can open the working environment to provision storage.
---

= Provisioning storage for ONTAP clusters
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

After you discover your ONTAP cluster from Cloud Manager, you can open the working environment to provision storage.

== Creating volumes for ONTAP clusters

Cloud Manager enables you to provision NFS and CIFS volumes on ONTAP clusters.

.Before you begin

NFS or CIFS must be set up on the cluster. You can set up NFS and CIFS using System Manager or the CLI.

.About this task

You can create volumes on existing aggregates. You cannot create new aggregates from Cloud Manager.

.Steps

. On the Working Environments page, double-click the name of the ONTAP cluster on which you want to provision volumes.

. Click *Add New Volume*.

. On the Create New Volume page, enter details for the volume, and then click *Create*.
+
Some of the fields in this page are self-explanatory. The following table describes fields for which you might need guidance:
+
[cols=2*,options="header",cols="2,6"]
|===
| Field
| Description

| Size | The maximum size that you can enter largely depends on whether you enable thin provisioning, which enables you to create a volume that is bigger than the physical storage currently available to it.

| Access control (for NFS only) | An export policy defines the clients in the subnet that can access the volume. By default, Cloud Manager enters a value that provides access to all instances in the subnet.

| Permissions and Users / Groups (for CIFS only) | These fields enable you to control the level of access to a share for users and groups (also called access control lists or ACLs). You can specify local or domain Windows users or groups, or UNIX users or groups. If you specify a domain Windows user name, you must include the user's domain using the format domain\username.

| Usage Profile | Usage profiles define the NetApp storage efficiency features that are enabled for a volume.

| Snapshot Policy | A Snapshot copy policy specifies the frequency and number of automatically created NetApp Snapshot copies. A NetApp Snapshot copy is a point-in-time file system image that has no performance impact and requires minimal storage. You can choose the default policy or none. You might choose none for transient data: for example, tempdb for Microsoft SQL Server.
|===

== Replicating data

You can replicate data between Cloud Volumes ONTAP systems and ONTAP clusters by choosing a one-time data replication, which can help you move data to and from the cloud, or a recurring schedule, which can help with disaster recovery or long-term retention.

link:task_replicating_data.html[Click here for more details].

== Using ONTAP as persistent storage

Cloud Manager can automate the deployment of NetApp Trident on Kubernetes clusters so you can use ONTAP as persistent storage for containers.

link:task_connecting_kubernetes.html[Click here for more details].
