---
sidebar: sidebar
permalink: task_planning_your_config.html
keywords: license, disk, ebs, storage, size, write speed, volume usage, explore, standard, premium, ec2, capacity, limit, configurations, virtual machine, vm, regions, supported disks, types, general purpose, gp2 provisioned IOPS, piops, throughput optimized, cold, SSD, HDD, st1, sc1, premium storage, standard storage, thin provisioning, deduplication, compression
---

= Planning your ONTAP Cloud configuration
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When you deploy ONTAP Cloud systems, you can choose a preconfigured system that matches your workload requirements, or you can create your own configuration. If you choose your own configuration, you should understand the options available to you.

toc::[]

== Choosing a license type

ONTAP Cloud is available in AWS and Azure in two pricing options: pay-as-you-go and Bring Your Own License (BYOL). For pay-as-you-go, you can choose from three configurations: Explore, Standard, or Premium.

=== ONTAP Cloud for AWS

In AWS, you can deploy ONTAP Cloud as a single system or an HA pair.

[cols=5*,options="header"]
|===
|
| Explore
| Standard
| Premium
| BYOL

| EC2 instance types for single node systems a|
* m3.xlarge
* m4.xlarge

a|
* c4.2xlarge
* m3.2xlarge
* m4.2xlarge
* r3.xlarge
* r4.xlarge

a|
* c4.4xlarge
* c4.8xlarge
* m4.4xlarge
* r3.2xlarge
* r4.2xlarge

a|
* c4.2xlarge
* c4.4xlarge
* c4.8xlarge
* m3.xlarge
* m3.2xlarge
* m4.xlarge
* m4.2xlarge
* m4.4xlarge
* r3.xlarge
* r3.2xlarge
* r4.xlarge
* r4.2xlarge

| EC2 instance types for HA pairs | m4.xlarge

a|

* c4.2xlarge
* m4.2xlarge
* r3.xlarge
* r4.xlarge

a|

* c4.4xlarge
* c4.8xlarge
* m4.4xlarge
* r3.2xlarge
* r4.2xlarge

a|

* c4.2xlarge
* c4.4xlarge
* c4.8xlarge
* m4.xlarge
* m4.2xlarge
* m4.4xlarge
* r3.xlarge
* r3.2xlarge
* r4.xlarge
* r4.2xlarge

| EBS raw capacity limit | 2 TB | 10 TB
2+<a|
* 368 TB for single node systems
* 360 TB per node in an HA pair

| Term 3+| Hourly | 6 or 12 months

|===

Notes:

. Pay-as-you-go configurations are not supported in GovCloud (US).

. ONTAP Cloud encryption is not supported with M3 instances.

. When you choose an EC2 instance type, you can specify whether it is a shared instance or a dedicated instance.

. Enhanced write performance is supported when using EBS SSDs with ONTAP Cloud Standard, Premium, and BYOL, except when using M3 and R3 instance types with Standard and Premium.

. Tiered storage configurations are supported with ONTAP Cloud Standard, Premium, and BYOL, except when using M3 and R3 instance types when using Standard and Premium.

. For AWS region support, see the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].

=== ONTAP Cloud for Azure

In Azure, you can deploy ONTAP Cloud as a single node system.

[cols=5*,options="header"]
|===
|
| Explore
| Standard
| Premium
| BYOL

| Virtual machine types | DS3_v2

a|
* DS4_v2
* DS13_v2

a|
* DS5_v2
* DS14_v2

a|
* DS3_v2
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2

| Raw capacity limit | 2 TB | 10 TB 2+| 252 TB

| Term 3+| Hourly | 12 months

|===

Notes:

. The actual maximum capacity may be less because of virtual machine limits: 60 TB for DS3, 124 TB for DS4 and DS13, and 252 TB for DS5 and DS14.

. For Azure region support, see the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].

== Choosing an AWS disk type

When you create volumes for ONTAP Cloud systems, you need to choose the underlying EBS volume type (which ONTAP Cloud sees as a _disk_). You should choose the configuration that meets your requirements for performance and cost.

The underlying AWS disk type for ONTAP Cloud can be a single EBS disk type or a tiered storage configuration that uses EBS as a performance tier and S3 as a capacity tier. For an overview of storage tiering, see link:concept_storage.html[Storage].

=== Supported EBS disk types

At a high level, the differences between EBS disk types are as follows:

* General Purpose SSD disks balance cost and performance for a broad range of workloads. Performance is defined in terms of IOPS.

* Provisioned IOPS SSD disks are for critical applications that require the highest performance at a higher cost.

* Throughput Optimized HDD disks are for frequently accessed workloads that require fast and consistent throughput at a lower price.

* Cold HDD disks are meant for backups, or infrequently accessed data, because the performance is very low. Like Throughput Optimized HDD disks, performance is defined in terms of throughput.

NOTE: Cold HDD disks are not supported with ONTAP Cloud HA configurations.

For additional details about use cases, refer to http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html[AWS Documentation: EBS Volume Types^].

== Choosing an Azure disk type

When you create volumes for ONTAP Cloud systems, you need to choose the underlying Azure disk type. Each disk type is designed for different workloads. You should choose the disk that meets your requirements for both performance and cost.

The underlying disk type for Azure can be Premium Storage or Standard Storage:

* Premium Storage disks store data on solid state drives (SSDs). The SSD disks provide high performance for I/O-intensive workloads at a higher cost.

* If you do not need high IOPS, you can limit your costs by using Standard Storage disks which are backed by hard disk drives (HDD).

For additional details about the use cases for these disks, see https://azure.microsoft.com/documentation/articles/storage-introduction/[Microsoft Azure Documentation: Introduction to Microsoft Azure Storage^].

== Choosing a disk size

You can choose from several disk sizes when you launch ONTAP Cloud systems and when you use the advanced allocation option. You should consider the disk size carefully because it impacts cost, performance, and total volume and system capacity.

When you launch ONTAP Cloud instances, you must choose the default disk size for aggregates. Cloud Manager uses this disk size for the initial aggregate, and for any additional aggregates that it creates when you use the simple provisioning option. You can create aggregates that use a disk size different from the default by using the advanced allocation option.

When choosing disk size, you should take several factors into consideration. The disk size impacts how much you pay for storage, the size of volumes that you can create in an aggregate, the total capacity available to an ONTAP Cloud system, and storage performance.

Different disk sizes are available for each disk type. Note that all disks in an aggregate must be the same size.

=== How disk size relates to performance in AWS

The performance of EBS disks is tied to disk size. The size determines the baseline IOPS and maximum burst duration for SSD disks and the baseline and burst throughput for HDD disks.

Larger disks have a higher baseline and burst performance, so you should always consider performance along with cost. Ultimately, you should choose the disk size that gives you the sustained performance that you need.

For example, when using General Purpose SSD disks, you might choose the following disk sizes:

* 100 GB because you want to start out with something small or because you have low performance requirements

* 500 GB because you want to get the best price to performance ratio

* 4 TB because you need very high sustained IOPS performance

Even if you do choose larger disks (for example, six 4 TB disks), you might not get all of the IOPS because the EC2 instance (for example, r3.2xlarge) can reach its bandwidth limit.

For more details about the relationship between size and performance, refer to http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html[AWS Documentation: EBS Volume Types^].

=== How disk size relates to performance in Azure

The performance of Azure Premium Storage is tied to the disk size. Larger disks provide higher IOPS and throughput. For example, choosing 1 TB disks can provide better performance than 500 GB disks, at a higher cost. When sizing for performance, you should also be aware of performance limits tied to Azure virtual machine types.

https://azure.microsoft.com/documentation/articles/storage-premium-storage/[Microsoft Azure Documentation: Premium Storage: High-Performance Storage for Azure Virtual Machine Workloads^]

https://azure.microsoft.com/documentation/articles/virtual-machines-linux-sizes/[Microsoft Azure Documentation: Sizes for virtual machines in Azure^]

There are no performance differences between disk sizes for Standard Storage. You should choose disk size based on the capacity that you need.

== Choosing a write speed

Cloud Manager enables you to choose a write speed setting for single node ONTAP Cloud systems. Before you choose a write speed, you should understand the differences between the normal and high settings and risks and recommendations when using high write speed.

=== Difference between normal write speed and high write speed

When you choose normal write speed, data is written directly to disk, thereby reducing the likelihood of data loss in the event of an unplanned system outage.

When you choose high write speed, data is buffered in memory before it is written to disk, which provides faster write performance. Due to this caching, there is the potential for data loss if an unplanned system outage occurs.

The amount of data that can be lost in the event of an unplanned system outage is the span of the last two consistency points. A consistency point is the act of writing buffered data to disk. A consistency point occurs when the write log is full or after 10 seconds (whichever comes first). However, AWS EBS volume performance can affect consistency point processing time.

=== When to use high write speed

High write speed is a good choice if fast write performance is required for your workload and you can withstand the risk of data loss in the event of an unplanned system outage.

=== Recommendations when using high write speed

If you enable high write speed, you should ensure write protection at the application layer.

== Choosing a volume usage profile

ONTAP includes several storage efficiency features that can reduce the total amount of storage that you need. When you create a volume in Cloud Manager, you can choose a profile that enables these features or a profile that disables them. You should learn more about these features to help you decide which profile to use.

NetApp storage efficiency features provide the following benefits:

Thin provisioning:: Presents more logical storage to hosts or users than you actually have in your physical storage pool. Instead of preallocating storage space, storage space is allocated dynamically to each volume as data is written.

Deduplication:: Improves efficiency by locating identical blocks of data and replacing them with references to a single shared block. This technique reduces storage capacity requirements by eliminating redundant blocks of data that reside in the same volume.

Compression:: Reduces the physical capacity required to store data by compressing data within a volume on primary, secondary, and archive storage.

== AWS network information worksheet

When you launch ONTAP Cloud in AWS, you need to specify details about your VPC network. You can use a worksheet to collect the information from your administrator.

=== Network information for ONTAP Cloud

[cols=2*,options="header",cols="30,70"]
|===

| AWS information
| Your value

| Region |
| VPC |
| Subnet |
| Security group (if using your own) |

|===

=== Network information for an ONTAP Cloud HA pair in multiple AZs

[cols=2*,options="header",cols="30,70"]
|===

| AWS information
| Your value

| Region |
| VPC |
| Security group (if using your own) |
| Node 1 availability zone |
| Node 1 subnet |
| Node 2 availability zone |
| Node 2 subnet |
| Mediator availability zone |
| Mediator subnet |
| Key pair for the mediator |
| Floating IP address for cluster management port |
| Floating IP address for data on node 1 |
| Floating IP address for data on node 2 |
| Route tables for floating IP addresses |

|===

== Azure network information worksheet

When you deploy ONTAP Cloud in Azure, you need to specify details about your virtual network. You can use a worksheet to collect the information from your administrator.

[cols=2*,options="header",cols="30,70"]
|===

| AWS information
| Your value

| Region |
| Virtual network (VNet) |
| Subnet |
| Network security group (if using your own) |

|===
