---
sidebar: sidebar
permalink: task_granting_aws_permissions.html
keywords: permissions, aws, policy, iam, instance, iam role, role, granting, policy, iam policy, iam user, iam group, access keys, custom launch
summary: If you cannot launch Cloud Manager in AWS from NetApp Cloud Central, then you must provide Cloud Manager with the permissions that it needs if you want to launch and manage Cloud Volumes ONTAP in AWS.
---

= Granting permissions when Cloud Manager is not launched from Cloud Central
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

If you cannot launch Cloud Manager in AWS from https://cloud.netapp.com[NetApp Cloud Central^], then you must provide Cloud Manager with the permissions that it needs if you want to launch and manage Cloud Volumes ONTAP in AWS.

.About this task

The Cloud Manager IAM policy defines the AWS actions and resources that Cloud Manager is allowed to use. You can grant the permissions defined in the IAM policy in one of two ways:

* You can attach an IAM role to the Cloud Manager instance in AWS.

* You can attach the IAM policy to IAM users or groups.
+
You would then specify the AWS access keys for those users in Cloud Manager.

.Steps

. Download the Cloud Manager IAM policy from the following location:
+
https://mysupport.netapp.com/cloudontap/iampolicies[NetApp OnCommand Cloud Manager: AWS and Azure Policies^]

. From the IAM console, create your own policy by copying and pasting the text from the Cloud Manager IAM policy.

. Grant permissions to the Cloud Manager instance or to IAM users:
+
[cols=2*,options="header",cols="25,75"]
|===
| Option
| Description
| Grant permissions to the Cloud Manager instance a|
.. Create an IAM role with the role type Amazon EC2 and attach the policy that you created in the previous step to the role.
.. Attach the IAM role to Cloud Manager when you launch it from the AWS Marketplace (choose *Custom Launch*) or by modifying an existing instance from the EC2 console.

| Grant permissions to IAM users | Attach the policy to IAM users or groups. For instructions, refer to http://docs.aws.amazon.com/IAM/latest/UserGuide/ManagingPolicies.html[AWS Documentation: Managing IAM Policies^].
|===

.Result

Cloud Manager now has the permissions that it needs. If you attached the policy to IAM users, you must specify the AWS access keys for those IAM users when you set up user accounts in Cloud Manager.
